### ISSUE TITLE
[BUG] same issue  as 'show_tags doesn't finish' #68 but with #tag

### ISSUE THREAD

**Issue by dietrich** [renerocksai/telekasten.nvim#102]
I have the same exact issue and outcome error as above but with tag_notation ="#tag".  And if I remove the # from the regular expression in tagutils.lua line 4, the code runs. Seems to be choking on #. If I switch to ":tag:" and then write a tag... it works.

**To Reproduce**
1. Start nvim
2. Telekasten show_tags
4. See error:
5. E5108: Error executing lua .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:493: 'rg --vimgrep -o (^|\s|'|")#[a-zA-Z]+[a-zA-Z0-9/\-_]* -- /home/dwlawren/obsidian' was unable to complete in 5000 ms
stack traceback:
        [C]: in function 'error'
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:493: in function 'wait'
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:447: in function 'sync'
        ...k/packer/start/telekasten.nvim/lua/taglinks/tagutils.lua:131: in function 'do_find_all_tags'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:2541: in function 'selection'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:2816: in function 'panel'
        [string ":lua"]:1: in main chunk

Error executing luv callback:
...k/packer/start/telekasten.nvim/lua/taglinks/tagutils.lua:47: attempt to perform arithmetic on local 'endpos' (a nil value)
stack traceback:
        ...k/packer/start/telekasten.nvim/lua/taglinks/tagutils.lua:47: in function 'split'
        ...k/packer/start/telekasten.nvim/lua/taglinks/tagutils.lua:93: in function 'parse_entry'
        ...k/packer/start/telekasten.nvim/lua/taglinks/tagutils.lua:120: in function '_user_on_exit'
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:238: in function '_shutdown'
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:45: in function <.../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:36>
        [C]: in function 'wait'
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:480: in function 'wait'
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:447: in function 'sync'
        ...k/packer/start/telekasten.nvim/lua/taglinks/tagutils.lua:131: in function 'do_find_all_tags'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:2541: in function 'selection'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:2816: in function 'panel'
        [string ":lua"]:1: in main chunk

**Operating system (please complete the following information):**
 - OS: WSL2 ubuntu 20.04

**Additional context**

**Comment by lambtho12** [comment]
I am currently looking into it. Could you please give a minimal markdown file that would showcase this issue?
Like 
```markdown
# Example
An example with a #tag issue
```

**Comment by dietrich** [comment]
# Example

## To get the above error (not doing anything special)
 - Telekasten show_tags

## Looking at tagutil.lua
-  local colon_re = "(^|\\s|'|\")#[a-zA-ZÀ-ÿ]+[a-zA-ZÀ-ÿ0-9/\\-_]*"
- - creates the error
### BUT breaking out the regex to long form:
- local hashtag_re = "(^#[a-zA-Z]+[a-zA-Z0-9/\\-_]* | \\s#[a-zA-Z]+[a-zA-Z0-9/\\-_]* | '#[a-zA-Z]+[a-zA-Z0-9/\\-_]* | \"#[a-zA-Z]+[a-zA-Z0-9/\\-_]*)"
- - Doesn't error.

**Comment by lambtho12** [comment]
This is really strange. Do you have any idea on what could cause this? I'd rather not edit all regexes in the codebase to break the "or" statements like that 😄

**Comment by lambtho12** [comment]
If you run the rg command directly on the terminal, does it work? 
I.E., in you zettelkasten home, try

```bash
rg --vimgrep -o "(^|\\s|'|\")#[a-zA-ZÀ-ÿ]+[a-zA-ZÀ-ÿ0-9/\\-_]*" .
```


I found [this discussion](https://github.com/BurntSushi/ripgrep/issues/2056) that may be relevant as well. Could you try it?

**Comment by dietrich** [comment]
### rg --vimgrep -o "(^|\\s|'|\")#[a-zA-ZÀ-ÿ]+[a-zA-ZÀ-ÿ0-9/\\-_]*" .
- works in the terminal

###  escaping issue? if I remove \\\s in  "(^|'|\"|\\\s)#[a-zA-Z]+[a-zA-Z0-9/\\-_]*"    
- it works.

discussion: sorry don't understand in this context what I should do.

**Comment by lambtho12** [comment]
If you remove `\\s` it may not crash, but it will output an incomplete list unfortunately. In my setup, if I run the original command in terminal, I have 410 matches, if I remove the `\\s`, I only have 8...

It is hard to debug this as I can not reproduce it myself on linux or Mac and do not have a windows machine at hand to try with WSL2.

I have nothing else in mind except maybe trying replacing `"-o"` by `"-o -e"` in
https://github.com/renerocksai/telekasten.nvim/blob/a1eca0bd91c3d9f9711168eef5165debf38dd3ef/lua/taglinks/tagutils.lua#L22

**Comment by dietrich** [comment]
I believe the issue was with ripgrep 11.0.2  Upgraded ripgrep to 13.0.0 and I no longer experience timeouts.  Thanks for this plugin... it's amazing productive.
