### ISSUE TITLE
[BUG] Doesn't update name correctly

### ISSUE THREAD

**Issue by dmytrodubinin** [renerocksai/telekasten.nvim#113]
**Please confirm**
- [ ] I am running the latest version of this plugin

**Describe the bug**

**To Reproduce**
1. Start nvim
2. rename_note with the name that ends with `m` letter
3. get new name without `m` letter. For example try to rename file `erich_fromm` to `Erich Fromm` end get uncorrect name: `Erich Fro`

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8066458/165516956-60c080a1-04b8-48bf-b572-33c518284e08.png)
It doesn't use `m` letter for name:
![image](https://user-images.githubusercontent.com/8066458/165517024-195011d5-ed07-460e-8e1b-fd98951aacd0.png)

**Operating system (please complete the following information):**
 - OS: Fedora 35

**Comment by lambtho12** [comment]
Wut? This is so strange. 
I can indeed reproduce and it seems that it is only with the letter `m`. I will look into that this envening.

**Comment by lambtho12** [comment]
15 minutes to solve the issue. Bet you did not expect that! It should work as expected now. Thank you for pointing it out.
