### ISSUE TITLE
[BUG] rename_update_links doesn't work

### ISSUE THREAD

**Issue by dmytrodubinin** [renerocksai/telekasten.nvim#117]
**Please confirm**
- I am running the latest version of this plugin

**Describe the bug**
When I rename file `rename_update_links` doesn't work. For example I have 2 files: `Erich Fromm` and `Escape from Freedom`. In second file I have `[[Erich Fromm]]` link. When I rename `Erich Fromm` file, link from another doesn't update (and I don't have any message about how many links updated, even if it's zero).

In config i have 
```
-- should all links be updated when a file is renamed
    rename_update_links = true,
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8066458/165691135-1e6e1e0f-9b29-4f69-a286-6d826eda8233.png)
![image](https://user-images.githubusercontent.com/8066458/165691255-a319a21c-4bda-4382-b966-b3eeb7f10346.png)
![image](https://user-images.githubusercontent.com/8066458/165691327-74feec20-3746-4e9f-8802-93d4ebc7d713.png)
But no message, file name updaded but link no:
![image](https://user-images.githubusercontent.com/8066458/165691457-228cad99-4954-4ece-8486-1ddb82c19a58.png)

**Operating system (please complete the following information):**
 - OS: Fedora 35

**Comment by lambtho12** [comment]
Seems like it never occurred to me that people would use spaces in the filenames...Sorry 😄 

Thank you for reporting all these small issues!

**Comment by dmytrodubinin** [comment]
Yes, I also usually do not use spaces in the titles, but if you use wiki links, it looks clearer. I do not plan to do this, but still someone can
