### ISSUE TITLE
Working with subdirectories

### ISSUE THREAD

**Issue by lambtho12** [renerocksai/telekasten.nvim#12]
Hi, thank you for this great plugin!

I have a rather large zettelkasten with one level of subirectories (I know, it is not the standard approach to ZK). I have an issue when I paste a link, as only the filename is pasted. Therefore I can not follow-through the link.
Would it be possible to have some modifiers when pasting a link that allow to paste a relative path instead? 

Before stumbling on your really feature-rich extension, I made my [own very simplistic telescope plugin](https://gitlab.com/thlamb/telescope-zettel.nvim). I made it so the link could be formatted in different ways upon paste to circumvent this issue (maybe there could even be an option to always paste links a certain way).

**Comment by renerocksai** [comment]
Done!

Inserted links will keep the sub-directory component(s) if they are not pointing to daily or weekly notes :smile: 

Hope that helps!

**Comment by renerocksai** [comment]
I just checked with your code: there is a major difference between our implemented concepts of 'relative path': your code always creates links relative to the current note. 

Telekasten has no concept of the current note. So if you link from one note within `testdir/` to another note `other.md` within `testdir/`, you would just place a `[[other]]`, whereas telekasten would place it like this: `[[testdir/other]]`.

Can you live with that?

**Comment by lambtho12** [comment]
I only use my ZK from neovim, so as long as the note opens without issue when using `follow_link()`, I do not have a major issue with that.

However, maybe that could be a problem for people using something to render their markdown notes as a webpage (using neuron for instance). Not sure about that.

Thank you very much for the (very) quick reply and solution to this issue!

**Comment by renerocksai** [comment]
Thx for the quick reply! 

I also thought about other tools. My go-to reference for compatibility is [Obsidian](https://obsidian.md). It works with links the way telekasten produces now. In Obsidian, sub-dirs are optional, so it still works.

Regarding static-site generators and such: I would think that they should be happy with being provided non-ambiguous path information. I would hope that they support subdir-including links for links pointing to the same subdir. If not, I, personally, would consider link substitution as a part of the generation step and pre-process the notes to strip off un-necessary subdirs. 

Maybe I can implement a feature that goes through all notes and does the stripping... At one's own risk. 

Thx for the pointer, I'll definitely check out neuron! If it supports some config option that helps it deal with un-stripped subdir-containing links, I'll better document it somewhere in the readme.

**Comment by renerocksai** [comment]
Update: just checked out neuron. What a beast! :smile: . The way I understand it, is that neuron at least does not require to specify subdirs in links. No idea what it does when it encounters them. 

Given that your subdir style of working and linking is a very sane option, I suggest waiting until an issue with subdir-containing links comes up.

**Comment by lambtho12** [comment]
> I would think that they should be happy with being provided non-ambiguous (context-free) path information.

True, it may be much simpler for them to do so.

>  I'll definitely check out neuron

I think neuron is being deprecated in favor of [emanote](https://note.ema.srid.ca/). I never tested it but apparently it works with `polymorphic (in filetype, and path signifier) wiki-links: [[Foo]], [[Bar/Qux]], [[Examples/Program.py]]`

**Comment by lambtho12** [comment]
> I suggest waiting until an issue with subdir-containing links comes up.

Agree with you on that. I tested 35f4e6342f6d73d179c5af0b741b643b312e7458 and it seems to be everything that I wished for :smile: 

Thanks again!

**Comment by renerocksai** [comment]
Welcome! :blush:
