### ISSUE TITLE
[BUG] Preview image doesn't work if img directory is outside home (one up)

### ISSUE THREAD

**Issue by quesada** [renerocksai/telekasten.nvim#132]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**
Preview image doesn't work if img directory is outside home (one up) 
**To Reproduce**
use this on init.vim:

```
    local home = vim.fn.expand("/home/q/Seafile/LSnotes/pages")
    require('telekasten').setup({
    home         = '/home/q/Seafile/LSnotes/pages',
    ...
    image_subdir = "../assets",

```
Note the assets directory is one up from home

Then when I try to preview an image, with `lua require('telekasten').preview_img()<CR>`

I get an empty box showing no files with the following on the search box:
> ../assets/pasted_img_20220512235309.png

**Screenshots**
![image](https://user-images.githubusercontent.com/182207/168176192-2002a958-8da2-469b-ae63-fd30c952db56.png)

**Operating system (please complete the following information):**
 - OS: Manjaro linux

**Comment by lambtho12** [comment]
Can you try putting an absolute path for `image_subdir`?
In your example, that would be
```lua
image_subdir = "/home/q/Seafile/LSnotes/assets"
```

**Comment by quesada** [comment]
> Can you try putting an absolute path for `image_subdir`? In your example, that would be
> 
> ```lua
> image_subdir = "/home/q/Seafile/LSnotes/assets"
> ```
> 
> `image_subdir` should either be a proper subdirectory (not a relative path outside of home) or an absolute path.

Tried this. 
I edited the filepath by hand, and trying image preview (leader zp), I get the following message:

![image](https://user-images.githubusercontent.com/182207/168283468-102bd695-82c9-4ff8-b218-0709ed9a9a1a.png)

Removing the path completely and using just the filename shows this error (missing the assets directory): 

![image](https://user-images.githubusercontent.com/182207/168283906-854a84db-38c2-4c08-9584-82bab8fdf5b3.png)
