### ISSUE TITLE
[BUG] show_tags lists template files

### ISSUE THREAD

**Issue by chrsm** [renerocksai/telekasten.nvim#133]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**

Not actually sure if this is a "bug" or intended, but `show_tags` lists tags in template files.

For instance, I have a template at `templates/new_note.md` that includes the following line to make it easier to add tags to new notes.

```
<!-- tags: #untagged -->
```

`:Telekasten show_tags` lists this file and `#untagged`.

**To Reproduce**

1. Create a template with a tag inside of it (eg `templates/new_note.md`)
1. Start nvim
2. Run `:Telekasten show_tags`
3. Observe the tag being included in the list

**Expected behavior**

I personally expected that the template document and its tags would _not_ be listed here.

**Screenshots**

![image](https://user-images.githubusercontent.com/1082451/168690506-a48ff494-0010-4fbc-9fac-7fab14d5f5ad.png)

**Operating system (please complete the following information):**
 - OS: mac, linux

**Comment by chrsm** [comment]
Side-note: it's possible to do this with `.ripgreprc`, so if this is intended behavior, you can close this up. It would, however, prevent any directory with the word "templates" in it from being searched - rather than just the telekasten-configured `templates` directory.

`.ripgreprc`
```
--glob=!**/templates/*.md
```

**Comment by lambtho12** [comment]
I agree with you, we should exclude templates from the tag list.
I tried playing around a bit with `--glob`. I can't seem to make it work using a full path. Ideally we would retrieve the path set by the user for the template directory and pass it to `rg --glob`, but I am not sure if that works with a full path.

**Comment by chrsm** [comment]
I wasn't able to get it to work with the full path either. My guess is that the plugin would need to figure out if `config.templates` is relative to `config.home` and chop it to use in the glob. I'll poke around when I have some time tonight.

**Comment by lambtho12** [comment]
I think this is the fix yes.

There are basically two cases:
1. **Template dir is outside of ZK home**. In that case, templates are never included in the `rg` search as we explicitly ask ripgrep to look for tags inside the ZK `home` directory.
2. **Template dir is a subdir of ZK home**. Then we can indeed take the relative path between the template dir and the home and use that as the glob. Fairly simple to do with Pleanry's Path functions. I will work on fixing that whenever I find 10 minutes to spare.

**Comment by chrsm** [comment]
@lambtho12 thank you! very much appreciated :-)
