### ISSUE TITLE
[BUG] new note filename is always uuid

### ISSUE THREAD

**Issue by amahmod** [renerocksai/telekasten.nvim#134]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**

I am using the default config provided in the README.
When I create a new note, the note file name is always `uuid` instead of note `title`.

I have tried changing the config value of  `new_note_filename` to other available values but the behavior is the same.

NVIM: `v0.7.0`
Node: `v16.15.0`
Npm: `8.5.5`

**To Reproduce**
1. Start nvim
2. Run command `Telekasten new_note`
3. Create a new note with any title
4. Note file name will contain only `uuid`

**Expected behavior**
I expected the new not file name will contain note `title`.

**Screenshots**
![telekasten-2022-05-20_12 06 28](https://user-images.githubusercontent.com/22317231/169464744-913172e3-c0b3-4277-907d-107d28d9eee7.gif)

**Operating system (please complete the following information):**
 - OS: `Arch Linux`

**Additional context**

**Comment by lambtho12** [comment]
I confirm. Look on it now.

**Comment by amahmod** [comment]
It works now. Thank you

**Comment by monomadic** [comment]
There's actually still a bug relating to this. When you escape (cancel) entering a title, it creates a uuid-generated file anyway on your disk, which you have to manually go and delete. Expected behavior of a cancellation should have no effect on your filesystem.

**Comment by amahmod** [comment]
> There's actually still a bug relating to this. When you escape (cancel) entering a title, it creates a uuid-generated file anyway on your disk, which you have to manually go and delete. Expected behavior of a cancellation should have no effect on your filesystem.

This is also happening to me.

**Comment by lambtho12** [comment]
Ok. I created a separate issue for that
