### ISSUE TITLE
[Question]: Note lookup by front matter aliases

### ISSUE THREAD

**Issue by dzintars** [renerocksai/telekasten.nvim#137]
**Please confirm**
- [x] I am running the latest version of this plugin

**Tell us about what's bothering you...**
I love the idea of this tool. :) Thank You for making it.

I am looking for a way to find notes via the front matter aliases.
In Obsidian i utilize this feature heavily.
I have thousands of notes and filenames are something like `202020121640.md`. So looking by file name does not make any sense.
Then in every note i have
```md
---
aliases: [Neovim, Nvim]
---
```
This effectively let me search the note by those aliases in Obsidian. When looking note by itself, and when linking to that note.
This way, i don't care about the file structure at all. Naming every file is ... not an option.
And i can rename the note at any time, because it is linked by that file name.
If only this feature, i think i would abandon Obsidian because switching the apps is a pain.
![image](https://user-images.githubusercontent.com/547420/171637901-8e9aa4b6-c0c6-4eee-91e1-84e18c9786ab.png)
This is how i look for notes
![screen-06 02 1](https://user-images.githubusercontent.com/547420/171639897-21ee5875-9f71-4ef1-8c13-39dd4170e234.png)
This is how i link to it.

Is it possible to achieve same behavior in Telekasten?

**Comment by dzintars** [comment]
Yes, you correct about the aliases.
I am not sure is aliases Obsidian specific thing, but i think they clearly represents the feature. `Title` is ... well, the general title of the note, which i personally don't use in Obsidian. Aliases is nice because of array. Sometimes ability to have multiple searchable aliases for a single file is helpful like you see in the `Neovim, Nvim` example.
Unfortunately i am not aware of the history of this project. Just found it couple hours ago and installed to evaluate it. 😃 
Idea about the `search_notes` could be a workaround. I will play with it. But... `search_notes` on its own is helpful feature so overriding it with regex would ruin original behavior.
I would love to see some kind `find_files_by_aliases` boolean or `find_files_by_pattern` option. Not sure about performance implications.

**Comment by lambtho12** [comment]
In lua, that mapping would be something like:
```lua
map(
  "n",
  "<leader>zga",
  ":lua require('telekasten').search_notes({default_text='^aliases: \\\\[([a-zA-Z].*,\\\\s*)*'})<CR>"
)
```

(I am bat at regex, but this should work).

**Comment by dzintars** [comment]
Yeah. Pattern definitely is much much more flexibe. Would love to search by `people` as well.

**Comment by dzintars** [comment]
`find_notes_by_pattern` would be better, because we also have multimedia files to be found which does not have front matter.

**Comment by lambtho12** [comment]
Is it really needed though? Such function would be essentially a wrapper for `search_notes` and would require the user to specify the pattern anyway. I don't really see the benefit of adding that, especially considering that the users can very easily create their own mappings for these tasks.

What you could do in your config is
```lua

-- Simpler mapping function
local function map(mode, lhs, rhs, opts)
  local options = { noremap = true }
  if opts then
    options = vim.tbl_extend("force", options, opts)
  end
  vim.api.nvim_set_keymap(mode, lhs, rhs, options)
end

-- Easy search_note by pattern
local function map_search_pattern(lhs, pattern)
  map(
    "n",
    lhs,
    ":lua require('telekasten').search_notes({default_text='"
      .. pattern
      .. "'})<CR>"
  )
end

-- Create custom search by patterns
map_search_pattern("<leader>zgp", "^people: \\\\[([a-zA-Z].*,\\\\s*)*")
map_search_pattern("<leader>zgl", "^location: \\\\[([a-zA-Z].*,\\\\s*)*")
map_search_pattern("<leader>zga", "^aliases: \\\\[([a-zA-Z].*,\\\\s*)*")
```

(Obviously, if all you YAML patterns are `pattern: [foo,bar]`, parts of the regex can go in the function itself to lighten the writing).

**Comment by dzintars** [comment]
https://github.com/renerocksai/telekasten.nvim/discussions/56#discussioncomment-1977177

**Comment by dzintars** [comment]
![image](https://user-images.githubusercontent.com/547420/171697659-fd2ffe49-8abd-41d0-98b5-276a12f07b0d.png)
I just tried `zk` and this seems to be the behavior i would expect to happen. But.. that's the external tool with built-in SQLlite. Not sure how it can relate to this project. Leaving just for an reference.

**Comment by renerocksai** [comment]
I think this issue can be closed. If not, why?

As described above, you can pass in an (escaped) regex to telescope from
`search_notes`. It will not find media files as the search is limited to
markdown files. Please re-open if you think closing it was wrong.
