### ISSUE TITLE
[FR] Wikipedia Links

### ISSUE THREAD

**Issue by lhoffjann** [renerocksai/telekasten.nvim#139]
**Describe the solution you'd like**
It would be nice to format the links like you do in Wikipedia or Obsidian.md by putting a | into the link and adding string afterwards.
it enables you to write sentences which are grammatically correct.

**Comment by lambtho12** [comment]
Agree. This is discussed in https://github.com/renerocksai/telekasten.nvim/discussions/56#discussioncomment-1977177

The problem is that this complicates everything quite significantly... Unfortunately, neither I nor renerocksai have the time to implement such a complex feature for now.

**Comment by IlyasYOY** [comment]
Hello @lhoffjann , I changed one line, so now I can navigate to wikilinks with aliases. I hope this solves at least one problem.
