### ISSUE TITLE
setting image_link_style = "markdown" not working [BUG] 

### ISSUE THREAD

**Issue by kraxli** [renerocksai/telekasten.nvim#140]
**Please confirm**
- [x] I am running the latest version of this plugin: yes

**Describe the bug and expected behavior**
In my setting I have `setting image_link_style = "markdown"` but the link included is `[[zettelkasten/my_link]]` instead of `[](zettelkasten/my_link)`

**Operating system (please complete the following information):**
 - OS: "Linux Mint 20 Ulyana"
 - neovim 0.7

**Comment by lambtho12** [comment]
Is it related to https://github.com/renerocksai/telekasten.nvim/issues/131 maybe?

**Comment by lambtho12** [comment]
I can't really reproduce the issue... When I use `insert_image_link` with a file that is already in `img`, it works as expected and insert `![](img/myimage.png)`.

But as in #131, the paste from clipboard stuff does not work.

Could you provide a bit more detail on what you are doing, what function you are calling, etc?

**Comment by kraxli** [comment]
it is about a link to a file by the function `lua require('telekasten').insert_link({ i=true })`. Sorry for being imprecise! I can I prove more details and in case which one best?

**Comment by lambtho12** [comment]
- `insert_link` inserts a link to a _note_. Currently, links to note can only be in wiki style: `[[link]]`
- The config option `image_link_style = "markdown"` only applies for _images_. To post a link to an image, you must use `insert_img_link`.

So I think there is a bit of misunderstanding here. If you would like markdown links for notes as well, there is already issues #139) and discussions about that (#56). Was that it?

**Comment by kraxli** [comment]
Ah sorry then I was really confused! Many thanks for the clarification!
