### ISSUE TITLE
[BUG] The yaml tag format regexp doesn't match the given example

### ISSUE THREAD

**Issue by alexander-gabriel** [renerocksai/telekasten.nvim#142]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**
The yaml tagline regexp fails where there are spaces between the surrounding brackets and the list of tags.

**To Reproduce**
1. Start nvim
2. create file using yaml tag format example given in documantation
```
---
title: My awesome note
date: 2021-12-06
tags: [ example, note-taking, foo, bar ]
---
```
4. try searching for tags
5. See error

**Expected behavior**
finds tags, regardless of spaces being present.
Would also be nice if the alternative yaml format
```
tags:
  - tag1
  - tag2
```
was supported

**Operating system (please complete the following information):**
 - OS: arch btw

**Additional context**
I love your work. Thank you so much!

**Comment by lambtho12** [comment]
Nice catch. I'll fix that right now. 

---
 
> Would also be nice if the alternative yaml format

Not sure about that one, I will not try to implement it unless you can come with a regex that would work. That being said, maybe a better idea would be to make a "custom" tag and let people come with their own regex.

**Comment by alexander-gabriel** [comment]
I think multiple, comma space separated tags (as given in the example) also foul the subsequent parsing.
I'm trying to debug this right now. 
I'm printing the tag variable in yaml_to_tags and that returns the whole list instead of single tags where more than one tag is specified.
so the splitting doesn't work either.

**Comment by lambtho12** [comment]
The splitting seems to be working, but somehow the picker only lists the first tag it seems. But if I type in the second tag, it is recognized as well.

**Comment by alexander-gabriel** [comment]
Hrm, I still get this error..
```
E5108: Error executing lua ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:2786: invalid option '%110' to 'format'
stack traceback:
        [C]: in function 'format'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:2786: in function 'entry_maker'
        ...scope.nvim/lua/telescope/finders/async_static_finder.lua:17: in function 'new_table'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:2780: in function 'selection'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:3021: in function 'panel'
        [string ":lua"]:1: in main chunk
```

**Comment by lambtho12** [comment]
? With the latest push ?

**Comment by alexander-gabriel** [comment]
yes

**Comment by lambtho12** [comment]
You had that before ?

**Comment by alexander-gabriel** [comment]
yes

**Comment by lambtho12** [comment]
Can you reproduce it with a minimal example? I have all my tags with `#tag`, and when I try to add a few `tags: [foo, bar]` in some notes, I do not have any specific error (besides the fact that the list only shows `foo` by default and not separate values for the other tags.

**Comment by alexander-gabriel** [comment]
I just set max_tag_len to 50. that does not throw an error. It seems the length of 110 (that is the actual value of that variable), is too long.
My tags aren't split though, the call runs and I see lots of tags that are comma separated tag lists just is they are in the file.

**Comment by alexander-gabriel** [comment]
![long-tags](https://user-images.githubusercontent.com/35339482/173240268-cd912b52-6a6b-46bd-998e-6add4b6942ed.png)

**Comment by alexander-gabriel** [comment]
Minimal crashing example note:

```
---
title: My awesome note
date: 2021-12-06
tags: [ with-a-really-really-long-tag-name-to-test-if-tagnames-kill-it-too-but-this-is-still-way-way-too-short ]                                                                    
---                                                                                                                                                                                                 
```
Another one:
```
---   
title: My awesome note
date: 2021-12-06  
tags: [ with, a, really, reaally, long, tag, name, to, test, if, tagnames, kill, it, too, but, this, is, still, way, short ]                                                        
---
```

**Comment by alexander-gabriel** [comment]
This one doesn't crash, but illustrates, that only the last tag is being extracted.
```
---   
title: My awesome note
date: 2021-12-06  
tags: [ first, middle, last ]                                                                                               
---  

```

**Comment by alexander-gabriel** [comment]
I suspect that the problem is that `"%s*.*%s*,"` matches greedily everything before the last comma, since the `.` also matches `,`.

**Comment by alexander-gabriel** [comment]
`"%s*%w*%s*,"`
this seems to work

**Comment by alexander-gabriel** [comment]
an no, it can't handle special characters like ä

**Comment by alexander-gabriel** [comment]
These do the job as far as my testing goes
```
"%s*%S*%s*,"
"%s*(%S*)%s*"
```
```

Tested with:

---
title: My awesome note
date: 2021-12-06
tags: [ tuäg1, ta2g, taßg3 ]
---
```

**Comment by lambtho12** [comment]
I am not sure I follow everything. What would be the final regex then?

https://github.com/renerocksai/telekasten.nvim/blob/b2ed311f281fc1400dbda183d997cc3f20e0471b/lua/taglinks/tagutils.lua#L7-L8

**Comment by alexander-gabriel** [comment]
that works fine.
the above mentioned regexes are from tagutils.lua lines 85 to 91

**Comment by lambtho12** [comment]
Aaaaaaaah ok, I see it now 😄 
I will push the fix in a few moments!

Thank you very much for making all the heavy lifting on that issue!
