### ISSUE TITLE
rg is not compiled with pcre2 support on ubuntu and opensuse

### ISSUE THREAD

**Issue by qwertzui11** [renerocksai/telekasten.nvim#145]
Hi, first of all, thx for this great plugin.

However when I try to use tags `telekasten.show_tags` I'm silently getting the error 

```
PCRE2 is not available in this build of ripgrep
```

after some googling I found out that my `rg` is not compiled with that flag enabled.

I tested `ubuntu 22.04` and `opensuse tumbleweed`.

So to use `telekasten` I'd have to use a local version of `rg` instead of the *distribution maintained* version. 

Which in my opinion is quite annoying and brings more maintenance to my setup. I guess the `rg` flag `--pcre2` got added due to [this color issue](https://github.com/renerocksai/telekasten.nvim/issues/115#issuecomment-1111385310)

Proposed solutions:
- only use `--pcre2` when `#tag` is getting used. not for `:tag:`
- document the need for `--pcre2` and why
- check if `--pcre2` is available and if so, use it, else not.
- remove the overall need of `--pcre2` :smiley: 

Thx for your time,
Cheers!

**Comment by lambtho12** [comment]
Indeed, the `--pcre2` flag was added to exclude the HTML color codes from tags. I did not known `--pcre2`was not a standard option.

I  the mean time, regarding what you propose, I think the cleanest way would be trying to completely remove the need of `--pcre2` while still being able to exclude the colors tags. However, I have absolutely no idea of how we could do that...
I am not really a pro when it comes to regex (I started using that for for this project basically), so I do not know if there is a better solution here. Any help would be appreciated

In the meantime, the second best solution would be to check if `--pcre2` is available or not. If it is, no issue. If it is not, then the users will be bothered by the `#color` stuff (if they also happen to use `#tag` notation. We can use a note with that in the readme and config examples. Do you know how we could implement such check?

**Comment by qwertzui11** [comment]
>  [..] the second best solution would be to check if --pcre2 is available or not. [...] Do you know how we could implement such check?

You could test for the feature like:
```bash
> echo 'hello' | /usr/bin/rg --pcre2 hello
PCRE2 is not available in this build of ripgrep
# command exited with code 2
> echo 'hello' | rg --pcre2 hello
hello
# command exited with code 0
```

> I the mean time, regarding what you propose, I think the cleanest way would be trying to completely remove the need of --pcre2 while still being able to exclude the colors tags. However, I have absolutely no idea of how we could do that...

How about not using regex at all. But instead use [treesitter](https://github.com/nvim-treesitter/nvim-treesitter) which is available to neovim.

Treesitter parses the markdown syntax and should give you a detailed AST about the markdown document.

However I myself never worked with treesitter, so I've no hands-on experience.

Any thoughts on treesitter?

**Comment by lambtho12** [comment]
> You could test for the feature like:
> 
> ```shell
> > echo 'hello' | /usr/bin/rg --pcre2 hello
> PCRE2 is not available in this build of ripgrep
> # command exited with code 2
> > echo 'hello' | rg --pcre2 hello
> hello
> # command exited with code 0
> ```

Yeah we could definitely do that in the setup of TK and then keep the result in config so we avoid re-testing every time we want to use regex. Good idea. 

---
> How about not using regex at all. But instead use treesitter which is available to neovim.

While I like treesitter very much, I am not a fan of forcing people to add yet another dependency (`rg` is already needed for telescope). Besides that, TK uses `rg`quite extensively already (as well as telescope). So it would be a pain to rewrite everything to avoid it. Finally, I have never actually worked with treesitter either. This can be rather difficult to do, as we need to parse non-opened buffers (finding tags in all notes), we need to be able to work with non-markdown files (.wiki, .zettel, .whatever), etc.

**Comment by qwertzui11** [comment]
> Yeah we could definitely do that in the setup of TK and then keep the result in config so we avoid re-testing every time we want to use regex. Good idea.

Good thinking. How about a `setup` setting `use_pcre2` with the options `no`, `yes` and `auto`. Default `auto` which tests `rg`.

---

> This can be rather difficult to do, as we need to parse non-opened buffers (finding tags in all notes), we need to be able to work with non-markdown files (.wiki, .zettel, .whatever), etc.

Makes sense!

**Comment by lambtho12** [comment]
> Good thinking. How about a `setup` setting `use_pcre2` with the options `no`, `yes` and `auto`. Default `auto` which tests `rg`.

There is already a billion options for TK. I may time the impact of running the test at each startup, but it should be fairly small anyway, so we might as well always do it to limit the number of options. Besides, some people use the same neovim config on different machines (my personal laptop has Arch (btw) and my work computer is a Mac). I'd rather avoid having to maintain two different configs for such small feature.

**Comment by lambtho12** [comment]
Finally found some time for this!

Could you checkout [this branch](https://github.com/renerocksai/telekasten.nvim/commits/144-fix-rg_pcre) and tell me if it works?

**Comment by qwertzui11** [comment]
works for, everything looks fine. Thx for your time!
