### ISSUE TITLE
Find_file not working after 1bd06e5d3642970f7cde3c2edb01631603c0b67e

### ISSUE THREAD

**Issue by lambtho12** [renerocksai/telekasten.nvim#15]
After the latest commit (1bd06e5d3642970f7cde3c2edb01631603c0b67e), the `find_file` function is no longer working and returns the following error
```
E5108: Error executing lua ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:490: attempt to get length of local 'filename' (a nil value)
stack traceback:
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:490: in function 'follow_link'
        [string ":lua"]:1: in main chunk
```

This is the case no matter what type of link I have (direct filename or some/dir/filename). 

The error goes away when I put a `#` after the filename, but then telescope does not return anything.

Moreover, **tt seems that it only looks for the heading part and not the filename.** So if I have multiple files that share the same heading (`## Introduction`), following link `[[file1#introduction]]` will output all files with a heading called `# Introduction` and not the correct file at the correct place.

**Comment by renerocksai** [comment]
Thx for reporting this. I am investigating!

**Comment by renerocksai** [comment]
It was a silly uninitialized variable. Initializing it was something the LSP had criticized half-way through implementing special links - and now it bit us. 

Thanks for pointing this out! :+1:
