### ISSUE TITLE
[BUG] path.lua:503: FileNotFoundError

### ISSUE THREAD

**Issue by adrianocorrea** [renerocksai/telekasten.nvim#151]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**
After installing Telekasten (with the required dependencies, including Plenary and Telescope) using either VimPlug or Packer on Windows 11 and WSL2, and executing `:Telekasten new_note` one gets the following error:

```
Telekasten.nvim: home folder \Users\MyUser\zettelkasten does not exist! Shall I create it? [y/N] yE5108: Error executing lua ...ocal\nvim-data\plugged\plenary.nvim/lua/plenary/path.lua:503: FileNotFoundError
stack traceback:
        [C]: in function 'error'
        ...ocal\nvim-data\plugged\plenary.nvim/lua/plenary/path.lua:503: in function 'mkdir'
        ...cal\nvim-data\plugged\telekasten.nvim/lua/telekasten.lua:245: in function 'check_dir_and_ask'
        ...cal\nvim-data\plugged\telekasten.nvim/lua/telekasten.lua:267: in function 'global_dir_check'
        ...cal\nvim-data\plugged\telekasten.nvim/lua/telekasten.lua:2099: in function 'selection'
        ...cal\nvim-data\plugged\telekasten.nvim/lua/telekasten.lua:3032: in function 'panel'
```

After manually creating the folder and sub-folders (e.g. daily, weekly, etc), one still gets the same error when making news notes. 

`:checkhealth` shows no errors.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start nvim
2. Run `:Telekasten new_note`
3. See prompt "Telekasten.nvim: home folder \User\MyUser\zettelkasten does not exist! Shall I create it? [y/N]"
4. Press "y"
5. See error

**Expected behaviour**
The expected behaviour would be Telekasten creating the zettelkasten home folder. 

**Operating system (please complete the following information):**
 - OS: Windows 11
 - OS: WSL2
 - NVIM: v0.7.0

**Comment by adrianocorrea** [comment]
The error above is the output on Windows 11, running nvim-qt.exe. On WSL2, the error message is the following (which does not show the "\" in the paths):

```
Telekasten.nvim: home folder /home/myuser/zettelkasten does not exist! Shall I create it? [y/N] yE5108: Error executing lua ...site/pack/packer/start/plenary.nvim/lua/plenary/path.lua:503: FileNotFoundError
stack traceback:
        [C]: in function 'error'
        ...site/pack/packer/start/plenary.nvim/lua/plenary/path.lua:503: in function 'mkdir'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:245: in function 'check_dir_and_ask'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:267: in function 'global_dir_check'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:2099: in function 'selection'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:3032: in function 'panel'
        [string ":lua"]:1: in main chunk
``` 
However, it seems to be the same error. 

About the binaries, they were installed with homebrew (including neovim), so they should not be substantially different from the ones running on most MacOS and some "standard" Linux distros.

**Comment by lambtho12** [comment]
Hard to debug as I do not have windows myself.

Could you manually create the folders (outside of nvim) and then post what happens ?

**Comment by adrianocorrea** [comment]
It seems that the `CleanPath` function is causing the bug. I have proposed a bug fix in #152.

**Comment by mingyar** [comment]
Hey guys!
It looks that I getting the same issue, but I'm on MacOS here.

Steps to reproduce the behaviour:

Start nvim
Run :Telekasten new_note
See prompt "Telekasten.nvim: home folder \User\MyUser\zettelkasten does not exist! Shall I create it? [y/N]"
Press "y"
See error
````
Telekasten.nvim: home folder ~/zettelkasten does not exist! Shall I create it? [y/N] yE5108: Error executing lua ...site/pack/packer/start/plenary.nvim/lua/plenary/path.lua:503: Fil
eNotFoundError
stack traceback:
        [C]: in function 'error'
        ...site/pack/packer/start/plenary.nvim/lua/plenary/path.lua:503: in function 'mkdir'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:238: in function 'check_dir_and_ask'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:260: in function 'global_dir_check'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:2103: in function 'selection'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:3072: in function 'panel'
        [string ":lua"]:1: in main chunk
````
I'm using LunarVim here and my plugin config look like this:
`````
{
    "renerocksai/telekasten.nvim",
    require('telekasten').setup({
      home                        = '~/zettelkasten',
      dailies                     = '~/zettelkasten/daily',
      weeklies                    = '~/zettelkasten/weekly',
      templates                   = '~/zettelkasten/templates',
      extension                   = ".md",
      take_over_my_home           = true,
      follow_creates_nonexisting  = true,
      dailies_create_nonexisting  = true,
      weeklies_create_nonexisting = true,
      template_new_note           = '~/zettelkasten/templates/new_note.md',
      template_new_daily          = "~/zettelkasten/templates/daily.md",
      template_new_weekly         = "~/zettelkasten/templates/weekly.md",
    })
````
Thanks in advance!

**Comment by renerocksai** [comment]
Please, see the readme. Don't use backslashes.

From the readme:

if you must use Windows, it is preferable to use C:/Users/myname/zettelkasten instead of ~/zettelkasten
NEVER use C:\Users\myname style paths
Using vim.fn.expand("~/zettelkasten") should work now but mileage will vary with anything outside of finding and opening files

**Comment by adrianocorrea** [comment]
Hi @mingyar,
Try setting the home variable outside the setup function. 
For example, you may do something like this in your `init.lua`:
```lua
local home = vim.fn.expand("~/zettelkasten")

require("telekasten").setup({
   home = home,
   dailies = home .. "/" .. "daily",
   -- ...
})
```
Let us know if it works.

**Comment by mingyar** [comment]
Thanks @renerocksai and @adrianocorrea!

It worked by doing:

`````
local home = vim.fn.expand("~/zettelkasten")

{
   "renerocksai/telekasten.nvim",
    require('telekasten').setup({
         home                        = home,
         dailies                     = home .. '/daily',
         weeklies                    = home .. '/weekly',
         templates                   = home .. '/templates',
         extension                   = ".md",
         take_over_my_home           = true,
         follow_creates_nonexisting  = true,
         dailies_create_nonexisting  = true,
         weeklies_create_nonexisting = true,
         template_new_note           = home .. '/templates/new_note.md',
         template_new_daily          = home .. "/templates/daily.md",
         template_new_weekly         = home .. "/templates/weekly.md",
       })
  },
`````
