### ISSUE TITLE
[FR] Feature full task management. 

### ISSUE THREAD

**Issue by shivanth** [renerocksai/telekasten.nvim#159]
**Is your feature request related to a problem? Please describe.**
I'm trying to use telekasten full time and one thing that I find painful is managing tasks. Obsidian has an awesome plugin [here](https://github.com/obsidian-tasks-group/obsidian-tasks)
**Describe the solution you'd like**
A fully functional task management that can support : 
1. Schedule tasks.
2. Recur tasks
3. Done date for task
4. Priority
5. Start date
6. Calendar integration.

**Describe alternatives you've considered**
Obsidian Tasks

**Additional context**
https://github.com/obsidian-tasks-group/obsidian-tasks

**Comment by lambtho12** [comment]
Personally I am not a fan of this idea. For me telekasten is first a note taking and organization plugin and should not try to become overly complex by doing many things simultaneously... But this is just my 2 cents.

Have you looked at [taskwarrior](https://taskwarrior.org/) and the various vim plugins that interface with it? You can do all functions you would like and many more.

**Comment by lambtho12** [comment]
As no one has voiced any opposition with my last comment and a few people (including @renerocksai) seems to agree with me as well, I mark this as wontfix and am closing this issue.

Feel free to re-open if you feel like it need to be reconsidered.
