### ISSUE TITLE
[BUG] No notes are found in telescope panel on any find command

### ISSUE THREAD

**Issue by alex-laycalvert** [renerocksai/telekasten.nvim#163]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**
Whenever I use any of the Telekasten find commands like `find_notes()` or `find_daily_notes()`, the find window appears but does not show any results, even when I can see my notes in the home for my notes. Telescope works just find and `rg` is installed and executable on my machine. Creating notes also works just fine and they are created in the expected directories. I do not believe it is just taking too long to find the notes because I have waited several minutes with not results, and Telescope, again, is functioning properly.

Tested on my main machine instead of my MacBook and this only seems to happen on macOS. My Arch setup runs just fine.

You can see my config [here](https://github.com/alex-laycalvert/dotfiles/blob/main/.config/nvim/lua/org.lua)

**To Reproduce**
1. Start nvim
2. Use `find_notes` or any other Telekasten find command
3. Nothing is show in find window
4. Cry

**Expected behavior**
I expect to see all of the correct files such as daily, weekly, or generic notes in my home for my notes.

**Screenshots**
I've expanded my filetree on the left-hand side so you can see all of the notes that I have.

<img width="1440" alt="Screen Shot 2022-09-22 at 12 43 05 PM" src="https://user-images.githubusercontent.com/45835678/191805007-68a8eea4-9e3f-4c0a-955b-7f3c0a4288eb.png">

**Operating system (please complete the following information):**
 - OS: macOS 12.4 Monterey

**Additional context**
It's possible that I am not ordering my notes correctly or there's something going on with the sub directories, I really don't know. It may just be a macOS issue.

**Comment by alex-laycalvert** [comment]
This also seems to cause an issue creating some new notes. After I enter the title, the finder window pops up again with no results and since the `selection` is nil I cannot select the new note I just created.

**Comment by alex-laycalvert** [comment]
After playing with my config, I found out the issue was that in my `telescope` config I ignore `.git` directories and I was keeping my notebook files inside a git directory. Problem is solved if I either remove the ignore file from my `telescope` config or keep my notes in a different directory.

**Comment by lambtho12** [comment]
Glad you found out! Not in a million years would have I guessed that! :smile:
