### ISSUE TITLE
[Bug] Weekly folder properly set to `nil` following user configuration

### ISSUE THREAD

**Issue by andy941** [renerocksai/telekasten.nvim#177]
**Please confirm**
- [ x] I am running the latest version of this plugin

**Tell us about what's bothering you...**
...
Hi, I was trying to get started with the plugin (lots to unpack) so forgive me if this is a naive question.
I don't want the "weekly" notes folder, I am not planning to use it, but every time I start the plugin to create a new note I am asked if I want to create the `weekly/` folder, to which I say no. Is it possible to suppress the message or having the weekly notes folder it's mandatory?

![image](https://user-images.githubusercontent.com/49410235/197420402-61d77bc4-d770-47a2-898b-f6d58957aa37.png)

Thank you,
Andrea

**Comment by lambtho12** [comment]
Did you try to set `weekly= nil` in your config? If I recall correctly this should prevent TK from asking if it should create the directory.

This should probably be documented somewhere if it is not the case.

**Comment by andy941** [comment]
Do you refer to `weeklies`? I tried both `weekly=nil` and `weeklies=nil`. Here is an example of what I have in my config:
``` lua
-- dir names for special notes (absolute path or subdir name)
	dailies = home .. "/" .. "daily",
	weeklies = nil,
	templates = home .. "/" .. "templates",
```
The rest of the config works as  expected, is mostly a copy and paste of the default config provided in the README.md.
I tried a quick fuzzy search in the docs to look for a solution but I couldn't find anything related to this. If I answer that I don't want the weekly folder to be created the setup exits and I can't even use the plugin. Maybe I'm missing something though.

Thanks for the help!

**Comment by lambtho12** [comment]
Yes, `weeklies` indeed, sorry.

I think you found an issue😄 . The `check_dir_and_ask` should skip the check if the user specified the dir as `nil` ([here](https://github.com/renerocksai/telekasten.nvim/blob/60808e8e596f2dc93db746b3437caf6716387f7d/lua/telekasten.lua#L232-L259)). But it seems that when telekasten is setup (when you open nvim), it does not overrides the default value when the user sets the folder to `nil`.

I will look into that this evening.

**Comment by lambtho12** [comment]
Mmmm, now that I think a bit more about it, it is probably not wise to allow setting `weeklies` as `nil` in the current implementation. The check_dir function is embedded in almost all pickers and should be properly refactored before, otherwise it will lead to more bugs down the line.

As a temporary bugfix, you could create an empty weekly folder somewhere where it does not bother you. I will work on that as soon as possible.

**Comment by andy941** [comment]
Ok thanks very much, no bother!

**Comment by lambtho12** [comment]
I set everything to default to the home directory in case it is not set. 
Now people that do not want to use special directories should no longer be bugged uselessly.
