### ISSUE TITLE
[BUG] ToggleTodo from normal mode sometimes takes last visual mode marks

### ISSUE THREAD

**Issue by j-w-e** [renerocksai/telekasten.nvim#178]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**
When calling the function toggle_todo() from normal mode, the ToggleTodo function sometimes acts on the last visual selection, not the current line. 

**To Reproduce**
1. Start nvim
2. Open a telekasten note
3. Visually select some content.
4. Hit esc to cancel visual selection. (More generally, do something to return to normal mode, eg y to yank.)
5. Move to a different line.
6. Call `:lua require('telekasten').toggle_todo()<cr>`
7. toggle_todo() acts on the lines of the previous visual selection, not the current line.

**Expected behavior**
From normal mode, toggle_todo() should always act on the current line. 

**Operating system (please complete the following information):**
- MacOS 11.7
- NVIM 0.8.0

**Comment by lambtho12** [comment]
This was likely introduced in #165. @alex-laycalvert , do you have some time to look into it?

**Comment by alex-laycalvert** [comment]
Sure, I can look at it today.

**Comment by alex-laycalvert** [comment]
It's happening because of how I originally checked for if you were toggling todo from a range or not. I just checked if the marks created from visual mode existed and if so, apply it to them.

**Comment by lambtho12** [comment]
Do you have an idea how to fix this? 
I tried to use `vim.api.nvim_get_mode().mode`, but executing the mapping (or typing the command) make it go back to normal mode, so it is not useful here.
A possibility would be to pass an option to the mapping, so we can have a mapping with no option and when we make the mapping for the visual mode, we could add an option 'visual' and then execute the code differently based on that.

That would work, but it won't be very elegant...

**Comment by lambtho12** [comment]
Ooops, I closed the wrong issue :sweat_smile:

**Comment by lambtho12** [comment]
I am extremely busy until mid-December and do not have time to look into that matter before then. If you propose a PR I may be able to review it though. If not, it will have to wait a bit unfortunately.

**Comment by alex-laycalvert** [comment]
Hi, I'm working on it now. Was incredibly busy for the past few weeks but I'll see what I can do now. If anyone happens to find a solution beforehand feel free to propose one.

**Comment by alex-laycalvert** [comment]
Ended using a `v = true` options for the toggle function. Not the most elegant but it works and is similar to the existing `i` param.

**Comment by alex-laycalvert** [comment]
Checkout PR #187
