### ISSUE TITLE
[BUG] Note title with special characters result in wrong filename

### ISSUE THREAD

**Issue by Schmiddiii** [renerocksai/telekasten.nvim#179]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**

Creating a note that contains `-` (and also other special characters like `+`) while prefixing the title with the UUID results in an incorrect note name:

- `a-b` -> `a-202211081846-a-b.md`
- `a+b` -> `a+b202211081846-a+b.md`

**To Reproduce**
1. Start nvim
2. `:Telekasten new_note`
3. Insert e.g. `a-b`
4. Filename is incorrect

**Expected behavior**

The filename to start with the UUID instead of (parts of) the title.

**Operating system (please complete the following information):**
 - OS: Linux (Arco Linux)

**Additional context**
- Neovim version 0.8.0.
- Parts of my config:

``` lua
require('telekasten').setup({
    -- ...
    prefix_title_by_uuid = true,
    new_note_filename = "uuid-title",
    uuid_type = "%Y%m%d%H%M",
    uuid_sep = "-",
})
```

**Comment by lambtho12** [comment]
[This line](https://github.com/renerocksai/telekasten.nvim/blob/60808e8e596f2dc93db746b3437caf6716387f7d/lua/telekasten.lua#L210) is the culprit. It looks like we must first sanitize the filename, otherwise it will return the original title as the subdir.

I will come with a fix this evening or tomorrow.

**Comment by lambtho12** [comment]
Closed with https://github.com/renerocksai/telekasten.nvim/commit/de4502bd558e05ce617df177acff2c1e86f39155

**Comment by Schmiddiii** [comment]
Works like expected, thank you.
