### ISSUE TITLE
[BUG] TK functions should not override default registers

### ISSUE THREAD

**Issue by IlyasYOY** [renerocksai/telekasten.nvim#184]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**

**To Reproduce**
1. Start nvim
2. Open vault
3. Yank anything
4. Put a cursor on any link 
5. Run follow_link command
6. Paste anything 
7. You got link text, not yanked text.

**Expected behavior**

Telekasten should preserve register state

**Comment by IlyasYOY** [comment]
I found this behaviour during source code analysis. 
I guess it's better to create more general task to preserve registers state during yanking and etc.

PS. OFC if this is not expected behaviour.

**Comment by lambtho12** [comment]
Agree with you, this is not ideal.
