### ISSUE TITLE
[FR] InsertLink with live grep

### ISSUE THREAD

**Issue by hayaokimura** [renerocksai/telekasten.nvim#188]
**Please confirm**
- [x] I am running the latest version of this plugin

**Is your feature request related to a problem? Please describe.**

I use telekasten.nvim with `new_note_filename = uuid`.
People who use telekasten.nvim with filename `uuid` like me must watch file contents one by one when using the current InsertLink function.
I guess Anyone sometimes wants to search a linking file with live grep.

**Describe the solution you'd like**

Add live grep to InsertLink function and enable it with `with_live_grep` option

**Describe alternatives you've considered**

**Additional context**

I created PR on my forked repository. Please refer to it when you want to see the implementation.
https://github.com/hayaokimura/telekasten.nvim/pull/1

**Comment by lambtho12** [comment]
This is a good point indeed and a much needed feature.
I just had a look at your fork, it seems reasonable.

Wouldn't it make sense to add a similar fix for `FindNote` ? (not sure as it would be redundant with `searchNotes` then point.

You can propose the PR here when you are ready and I will test it and merge tonight or tomorrow.

**Comment by lambtho12** [comment]
Do not forget to document the new option in the README and doc/telekasten.txt as well before making the PR.

**Comment by hayaokimura** [comment]
Thank you for replying!
I created PR. 
https://github.com/renerocksai/telekasten.nvim/pull/189

I worry about the option field value. Please read and reply to it.
https://github.com/renerocksai/telekasten.nvim/pull/189#discussion_r1032852374
