### ISSUE TITLE
[BUG] function InsertLink() not pasting link

### ISSUE THREAD

**Issue by PKlimo** [renerocksai/telekasten.nvim#190]
**Please confirm**
- [X] I am running the latest version of this plugin

**Describe the bug**
in function InsertLink()  line https://github.com/renerocksai/telekasten.nvim/blob/main/lua/telekasten.lua#L1453

```
filepath = selection.filename,
```
returns `nil`

**Additional context**
after changing line to 
```
                filepath = selection.filename or selection.value,
```
it seems to work, but I have no idea why. Maybe it is problem in my telescope configuration, but can't find, where the problem is and why `selection.filename` returns `nil` and `selection.value` returns correct file name.

**Comment by lambtho12** [comment]
just so I know before starting debugging this, if you use the `find_file` picker but select using `ctrl-I`, it should past the link instead of opening the file.

Does that work in you setup or does it show the same issue than `InsertLink`?

**Comment by cschmatzler** [comment]
I ran into this right now, so maybe I can give context - `C-I` works, `CR` leaves me with an empty `[[]]` as well.

**Comment by admilsonmarques** [comment]
> I ran into this right now, so maybe I can give context - `C-I` works, `CR` leaves me with an empty `[[]]` as well.

Just commenting, I have the same problem with the same behavior for `C-I` and `CR` while on the picker.

**Comment by lambtho12** [comment]
That should do it. I am not exactly sure why it stopped working, but at least it seems fixed now. Sorry for taking so long.

**Comment by cschmatzler** [comment]
Just confirming that acc5f0e fixed it. Thanks!
