### ISSUE TITLE
[BUG] NeoVim 0.9.0 crashes on config nvim: ../src/nvim/rbuffer.c:144: rbuffer_consumed: Assertion `count && count <= buf->size' failed.  

### ISSUE THREAD

**Issue by jeetsukumaran** [renerocksai/telekasten.nvim#199]
**Please confirm**

- [ X] I am running the latest version of this plugin

**Describe the bug**

Minimal Telekasten configuration (see below) results in NeoVim crashing on start when using NeoVim 0.9.0. This does not occur when using NeoVim 0.8.x.

```
nvim: ../src/nvim/rbuffer.c:144: rbuffer_consumed: Assertion `count && count <= buf->size' failed.
```

**To Reproduce**
1. Start nvim
2. See error

**Expected behavior**
NeoVim launches and I can start Telekasten.

Notes:

1. With Telekasten installed but no setup or the following dummy setup in my init.lua :

```
require('telekasten').setup({})
```

or  even

```
require('telekasten').setup({x="hello"})
```

then NeoVim launches, but of course when I try to run Telekasten I get the following error since it is not configured:

```
E5108: Error executing lua .../pack/telescope/start/telekasten.nvim/lua/telekasten.lua:3138: attempt to index field 'Cfg' (a nil value)
```

2. When using the default/recommended configuration or the following minimal configuration:

```
require('telekasten').setup({home=vim.fn.expand("~/zettelkasten")})
```
then NeoVim crashes on start with the above error.

3. This error is only with the latest version of NeoVim 0.9.x, not 0.8.x or earlier.

**Comment by renerocksai** [comment]
I am running neovim 0.9.0-dev-ef18c9f with Telekasten just fine. I haven't
touched my config in ages, though, and since then new options have been
added that I don't use / mention in my config. Would be interesting to see
what causes the bug. It really looks like something no Lua plugin should be
able to trigger easily.

I'll attach my config in a bit, maybe it helps you.

Jeet Sukumaran ***@***.***> schrieb am Mi., 4. Jan. 2023,
23:09:

**Comment by renerocksai** [comment]
Here is my config:

```vim
" Telekasten
lua << END
local home = vim.fn.expand('~/zettelkasten')
require('telekasten').setup({
    media_previewer = "viu-previewer",
	home = home,
	dailies = home .. "/" .. "daily",
	weeklies = home .. "/" .. "weekly",
	templates = home .. "/" .. "templates",

	-- image subdir for pasting
	-- subdir name
	-- or nil if pasted images shouldn't go into a special subdir
	image_subdir = nil,

	-- markdown file extension
	extension = ".md",

	-- following a link to a non-existing note will create it
	follow_creates_nonexisting = true,
	dailies_create_nonexisting = true,
	weeklies_create_nonexisting = true,

	-- templates for new notes
	template_new_note = home .. "/" .. "templates/new_note.md",
	template_new_daily = home .. "/" .. "templates/daily_tk.md",
	template_new_weekly = home .. "/" .. "templates/weekly_tk.md",

	-- image link style
	-- wiki:     ![[image name]]
	-- markdown: ![](image_subdir/xxxxx.png)
	image_link_style = "markdown",

	-- integrate with calendar-vim
	plug_into_calendar = true,
	calendar_opts = {
		-- calendar week display mode: 1 .. 'WK01', 2 .. 'WK 1', 3 .. 'KW01', 4 .. 'KW 1', 5 .. '1'
		weeknm = 4,
		-- use monday as first day of week: 1 .. true, 0 .. false
		calendar_monday = 1,
		-- calendar mark: where to put mark for marked days: 'left', 'right', 'left-fit'
		calendar_mark = "left-fit",
	},
    debug = false,

    close_after_yanking = false,
    insert_after_inserting = true,

    -- make syntax available to markdown buffers and telescope previewers
    install_syntax = true,

    -- tag notation: '#tag', ':tag:', 'yaml-bare'
    tag_notation = "#tag",

    -- command palette theme: dropdown (window) or ivy (bottom panel)
    command_palette_theme = "ivy",

    vaults = {
        second = { 
            home = "/home/rs/zettelkasten.test",
        }
    }
})
END
```

**Comment by jeetsukumaran** [comment]
Thanks! And yes, it's a weird bug because the point of crash is deep in NeoVim's C guts which is bizarre. Also messes up my terminal.

However, I continue to get this error even with your config as long as I run 0.9.0. Switching back to 0.8.0 and it works perfectly. Back and forth, and consistent results. Not sure what the problem is. 

Anyway, since this runs well for you, this might be a "me" problem. Later on I'll set up a virtual environment with minimal plugins so I can isolate the cause. Will post back here if I figure something out.

**Comment by lambtho12** [comment]
@jeetsukumaran any update on that? Do you still have the bug? Did you find a solution? Should I close this?

I am also using nvim 0.9.0 and as renerocksai, I do not have any issue...

```
NVIM v0.9.0-dev-813+g15394b6855
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by jeetsukumaran** [comment]
I updated to the next nvim snapshot a while back and have not encountered this again. So yes, please close.

**Comment by lambtho12** [comment]
Awesome, thank you. Do not hesitate to reopen if it happens again
