### ISSUE TITLE
Add an insert_note() that works with grep

### ISSUE THREAD

**Issue by lambtho12** [renerocksai/telekasten.nvim#21]
Sometimes I want to find an link a note whose title I do not know. In that case, I need to first do a search_notes() in order to find the appropriate note, then do the insert_note() with the correct title, or open the note and yank its name. Either case, this is a two-setp process which could be 1 step if I was able to paste the ID directly from a grep search.

This may actually be a really important feature for people that do not use title for their notes but just ID numbers, which is quite common in the ZK community I believe.

An other option (why not both?) is to implement telescope action mappings to the existing functions, so that pressing `<C-CR>` for instance would always paste the link.

**Comment by renerocksai** [comment]
Fantastic idea(s)!  I second the importance for people still using note IDs (which I had for quite a while, too). I will certainly dig into action mappings!  With those, I expect cool things to be possible like for instance, a nested telescope popup to select which heading or paragraph of a note to link to.

**Comment by renerocksai** [comment]
I just pushed 309eefe16b6699e34acd8b42fe966305f9268746 which should do the trick.

There are 2 new config options: 
- `close_after_yanking` : close telescope picker after yanking (false)
- `insert_after_inserting` : enter insert mode after inserting link from picker (true)

The keybindings are:

- <kbd>CTRL</kbd> + <kbd>i</kbd> : inserts a link to the selected note / image
  - the option `insert_after_inserting` defines if insert mode will be entered after the link is pasted into your
    current buffer
- <kbd>CTRL</kbd> + <kbd>y</kbd> : yanks a link to the selected note / image, ready for <kbd>p</kbd>asting
  - the option `close_after_yanking` defines whether the telescope window should be closed when the link has been
    yanked
- <kbd>RETURN / ENTER</kbd> : usually opens the selected note or performs the action defined by the called function
  - e.g. `insert_img_link()`'s action is to insert a link to the selected image.

I also put in mappings for `<C-CR>` but my terminal cannot do that. In my terminal, `C-CR`, `S-CR`, and `CR` all produce the same: `CR`.

In addition, now a `browse_media()` made sense: lets you browse your images etc. From there, you can yank or insert links to media files.

Of course, now that we can yank and insert links from every picker, this makes #20 even more important, so you don't end up with `[[./daily/2021-12-03]]` after inserting a link to a daily note you found via grep.

**Comment by lambtho12** [comment]
Fantastic!

> I also put in mappings for `<C-CR>` but my terminal cannot do that. In my terminal, `C-CR`, `S-CR`, and `CR` all produce the same: `CR`.

I said `<C-CR>` on top of my mind because I like to just remember one key and some modifiers. But I am not sure if this is actually feasible at all :sweat_smile:. In my extension, I think I could not make it work either and this is why I went with `<C-a>`, `<C-r>` and `<C-f>`.
