### ISSUE TITLE
Missing folders are not created when creating a new note

### ISSUE THREAD

**Issue by aleksey-rowan** [renerocksai/telekasten.nvim#217]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**
- Telekasten does not create intermediary folders if they don't exist when trying to create a new note.
- additionally, following a link to a non-existing note in a non-existing folder does not create either the missing folder or the desired note

I have [jghauser/mkdir.nvim](https://github.com/jghauser/mkdir.nvim) installed, but that doesn't help.

**To Reproduce**
1. Start nvim
2. run `Telekasten new_note`
3. type the name of a new note that is located in a non-existing folder
4. something like `new_folder/note`
5. See error
6. also, in an existing note create a link to a new note in a non-existing folder
7. something like `[[new_folder/note]]`
8. run `Telekasten follow_link`
9. observe Telescope opening with the note's name entered, but nothing in the listbox
10. pressing enter does not create a new note but instead switches to another open buffer

**Expected behavior**
Intermediary folders are created if they don't exist.

**Screenshots**
Error on the `Telekasten new_note` command:
![image](https://user-images.githubusercontent.com/79934725/217914779-66f94cc1-4f6e-4c91-b4ac-afe23a42f2e4.png)

Empty Telescope picker when following a link:
![image](https://user-images.githubusercontent.com/79934725/217916499-0cc19bb2-6024-4192-a14d-fd06890d94e7.png)

**Operating system (please complete the following information):**
 - OS: Ubuntu 22.04/WSL

**Comment by lambtho12** [comment]
Indeed, folders should be created on the spot. Thank you for pointing it out.

**Comment by lambtho12** [comment]
Started working on that (https://github.com/renerocksai/telekasten.nvim/commit/6290e52f971980ee15ccaf9dc0e225a159a8f7cc). It works for followlink, but the same fix does not work properly for create note. I do not know why (yet). Will revisit later an maybe try to refactor everything.
