### ISSUE TITLE
[FR] Keep old name in input field during rename

### ISSUE THREAD

**Issue by dmytrodubinin** [renerocksai/telekasten.nvim#218]
**Please confirm**
- [x] I am running the latest version of this plugin

![image](https://user-images.githubusercontent.com/8066458/218261752-5e0e4125-1302-490a-b4d2-b32853d5230b.png)

It would be nice to be able to just change the old file name, and not enter it completely again. Sometimes, when the file name is long, and you only need to change a couple of words, it is not very comfortable to enter it again.

It might be worth adding an option in the settings where you can choose between entering the full name of the file or changing the current name

**Comment by lambtho12** [comment]
Fixed. I agree, this is a very welcome improvement. Thanks for the suggestion.
I decided not to add an option to disable it. IMO there is already enough options like that. Adding extra ones for such small features are a bit over the top. We can revisit this decision obviously if it is a big issue.

I also left out the extension on purpose. I do not see any reason why a user would change the extension upon rename, so this spares a few key strokes to delete the extension or go over it.

While I was at it, I also enabled completion based on the existing files, so it may also save some time if the new filename is close to an already existing one.
