### ISSUE TITLE
[Getting Started][Installation]

### ISSUE THREAD

**Issue by fcarvalhopacheco** [renerocksai/telekasten.nvim#223]
**Please confirm**
- [x]  I am running the latest version of this plugin

Hi, I am just trying to install and use `telekasten.nvim` for the very first time. 
Here are some notes:

1. It seems that [Installation](https://github.com/renerocksai/telekasten.nvim#installation) is missing an Apostrophe.

<img width="903" alt="Screenshot 2023-02-19 at 6 56 25 PM" src="https://user-images.githubusercontent.com/37884899/220013942-0bf88e4e-bf5e-4eea-a7e6-94854e602343.png">

2. I am not a 100% sure about this but the it feels that the `( parenthesis )`  in the [Base-setup](https://github.com/renerocksai/telekasten.nvim#base-setup) section should be ` { Curly Brackets}` .

    - FROM this:
    ```lua
    require('telekasten').setup(
      home = '~/zettelkasten', -- Put the name of your notes directory here
    )
    ```
  
    To this??
    ```lua
    require('telekasten').setup{
      home = '~/zettelkasten', -- Put the name of your notes directory here
    }
    ```

- Thanks for creating this. I am excited to use this plugin.

**Comment by lambtho12** [comment]
Indeed. Thank you for reporting this. I made a few major edits to the doc last week to simplify the onboarding process for new users. There might be some other typos hiding here and there. Do not hesitate to report them or propose a PR to fix these.
