### ISSUE TITLE
[BUG]  Searching tags doesn't work

### ISSUE THREAD

**Issue by maxim-h** [renerocksai/telekasten.nvim#226]
**Please confirm**

- [x]  I am running the latest version of this plugin

**Describe the bug**
Pressing enter inside the `show_tags` gives empty picker with no results.

**To Reproduce**
1. Start nvim
2. Run `Telekasten show_tags`
3. Select any of your tags
4.  Press Enter
5. See empty telescope window with no results

**Expected behavior**
Selector of files with the searched tag.

**Screenshots**
Empty  window after selecting one of my tags (MDS).
![image](https://user-images.githubusercontent.com/22867431/220885102-69bec149-84cd-4673-8a5b-52ca169bf4fd.png)

**Operating system (please complete the following information):**
 - OS: Archlinux (Linux [hostname] 6.1.13-1-lts 1 SMP PREEMPT_DYNAMIC Wed, 22 Feb 2023 12:31:32 +0000 x86_64 GNU/Linux)

**Additional context**
After choosing the tag there is also this warning present
```
[telescope] [WARN  11:37:25] ...ig/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:467: Finder failed with msg:  ...d/telescope.nvim/lua/telescope/picker
s/entry_display.lua:53: bad argument #1 to 'ipairs' (table expected, got nil)
```

**Comment by lambtho12** [comment]
Can't reproduce.
Is your `tag_notation` option properly set? 

Can you provide a minimal example (config + one or two minimal files) so I can try to debug that?

**Comment by maxim-h** [comment]
I've tried all 3 tag notations. 
They are all recognized by `show_tags`. See screenshot:
![image](https://user-images.githubusercontent.com/22867431/220921605-5e4e80e1-db8b-4e15-bc17-0688f31152ff.png)

But non of them work once I choose a specific tag to search.

My minimalest config I could make:
```vim
if ! filereadable(system('echo -n "${XDG_CONFIG_HOME:-$HOME/.config}/nvim/autoload/plug.vim"'))
        echo "Downloading junegunn/vim-plug to manage plugins..."
        silent !mkdir -p ${XDG_CONFIG_HOME:-$HOME/.config}/nvim/autoload/
        silent !curl "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" > ${XDG_CONFIG_HOME:-$HOME/.config}/nvim/autoload/plug.vim
        autocmd VimEnter * PlugInstall
endif

call plug#begin(system('echo -n "${XDG_CONFIG_HOME:-$HOME/.config}/nvim/plugged"'))
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'renerocksai/telekasten.nvim'
call plug#end()

lua << EOF
local home = vim.fn.expand('/home/max/test')
require('telekasten').setup({
    home = home,
    -- tag notation: '#tag', ':tag:', 'yaml-bare'
    tag_notation = '#tags',
}
)
EOF
```
`/home/max/test` looks like this:

```sh
test
├── daily
├── img
├── templates
├── test_note.md
└── weekly
```

`test_note.md` has this inside:
```md
---
author: Me
date:  today
tags: [ tag1, tag2, tag3 ]
---

#test-tag

test text

#another_tag

:different-tag:
```

**Comment by lambtho12** [comment]
Just tried your minimal example, all 3 types of tags work as expected. `show_tags` finds them, selecting them opens a new picker that lets me select the note `test_note` and open it.

My setup is fully updated (all packages are in their most recent versions) and I am running `NVIM v0.9.0-dev-813+g15394b6855`

**Comment by lambtho12** [comment]
In theory, once you select your tag, telekasten will run the following:
`rg --vimgrep -e "<YOURTAG>" "--"`. Go in your `home` directory (the zk home, not `~/`) and try it with a known tag (`MDS`) for instance.

My guess is that `rg` does not return anything for some reason when you select a tag. This passes `nil` to telescope which is not happy about it.

**Comment by lambtho12** [comment]
So here is how it works:
1. Telekasten scrape your notes to make an index of the tags using `ripgrep` (for some reason, this works)
2. You select a tag in the list
3. It uses `ripgrep` again for this specific tag and display the result in a picker (this does not work for you)
4. You select the file in the picker, which opens it

So for some reason, it fails when trying to find a single tag. The command it tries to run is 
`rg --vimgrep -e "<YOURTAG>" "--"`
Can you try that in you home with a tag that exists?

**Comment by maxim-h** [comment]
Thanks for checking!

I did try `rg --vimgrep -e "<YOURTAG>" "--"` and it works completely fine. I see several files with this tag.
Actually, an unrelated problem, but here it doesn't distinguish whether <YOURTAG> is an actual tag (with #tag or :tag:) or just a word anywhere within the notes. Is that the intended behavior? 

But now that I've tested a little more I think I narrowed down the problem a bit. 
The search for the tags actually works. But the picker just doesn't display any results (see my screenshot from initial post). Despite that if I just ArrowDown once or twice and hit Enter it does successfully open a note that has this tag. 

So the issue is more in the picker not displaying anything. Do you think it can be an issue with `telescope` itself? Considering the fact that `find_notes` and `browse_media` work perfectly fine I'm doubtful of that. 

I'm using `NVIM v0.8.3`  and `PlugUpdate` says everything is already up-to-date.

**Comment by Inom-Turdikulov** [comment]
I have same issue, results invisible but I can select / open note (down->Enter).
```
  - OK: rg: found ripgrep 13.0.0
  - NVIM v0.8.3

rg --vimgrep -e "#example" "--"
content/inbox.md:3:7:tags: #example
```

I also tried downgrade rg, but it's not helped.

**Comment by lambtho12** [comment]
Would it be possible that you have some notes with a very strange filename (such as filenames with a `\n` in it)? See here https://github.com/renerocksai/telekasten.nvim/issues/180

**Comment by Inom-Turdikulov** [comment]
I tried remove all files except few, same issue. If I press `down->Enter` I'll open note with example tag. But it's not visible in preview.
![image](https://user-images.githubusercontent.com/3938577/224117255-c70f02b1-cd47-43d8-99b1-9754a4139c63.png)
![image](https://user-images.githubusercontent.com/3938577/224117422-f5793fa9-e924-44fb-9134-07bb25b266b6.png)

**Comment by maxim-h** [comment]
Tried reproducing the issue in a Rocky Linux VM (qemu; with kvm) running Gnome with minimal config.
Still the same problem.

**Comment by nesaro** [comment]
After playing with the function `FindAllTags`, I noticed that setting `show_link_counts` to false fixed it in my system

https://github.com/renerocksai/telekasten.nvim/blob/main/lua/telekasten.lua#L2675

**Comment by nesaro** [comment]
thanks @lambtho12 . I made a PR with the tiny change plus my understanding. I had the same issue in all my machines, and all of them work after changing the flag.

I suspect that there is something wrong around the function `generate_backlink_map`. I have never seen on my machine a count of links or backlinks like in the screenshots in the README.md, although reading the code `how_link_counts` is only set for the tags.

If the flag is not meant to be changed, I would need help to debug this thing properly to get to the bottom of it, as I have little experience in neovim/lua.
