### ISSUE TITLE
[BUG] Templates not visible when running `new_templated_note`

### ISSUE THREAD

**Issue by JMulder99** [renerocksai/telekasten.nvim#228]
**Please confirm**
- [x] I am running the latest version of this plugin downloaded via packer

**Describe the bug**
I have created a template for new notes, as well as daily and weekly notes and added them to the configuration. When running  `new_templated_note`, no templates show up in the fuzzy finder.

**To Reproduce**
1. Add templates to `~/zettelkasten/templates/` and add this path to `templates_new_note` etc in the setup.
1. Start nvim
2. Run :Telekasten new_templated_note
3. Create a file name
4. Check for templates in fuzzy finder
5. See error

**Expected behavior**
I would expect the list of three templates that I have created in `~/zettelkasten/templates/`.

**Screenshots**
No templates to select:
![image](https://user-images.githubusercontent.com/52777149/221835821-ce4ecd9c-e6a1-4e37-bba3-08d1f293a6fe.png)

Current configuration setup:

![image](https://user-images.githubusercontent.com/52777149/221836121-b0c7a415-5453-4266-b79b-525f1b5c3522.png)

Screenshot when running `debug = true`:

![image](https://user-images.githubusercontent.com/52777149/221835115-39f33da0-0340-4915-ab46-11a5d2778948.png)

**Operating system (please complete the following information):**
 - OS: CentOS, Linux

**Comment by lambtho12** [comment]
I cannot replicate, it works as expected on my side.

Does regular note/daily/weekly creation works as expected (i.e., it uses the template defined in the config)? Or does it start with a blank note?

**Comment by JMulder99** [comment]
I figured out a solution. The problem is caused by Lua not recognizing the tilde `~` in the path `"~/zettelkasten"` as home (at least on CentOS). So if you set `home="~/zettelkasten"`, it will ask you to create `~/zettelkasten` from within the current folder. This will end up looking like:

```
/user/name/
    Documents/
    Downloads/
        ~/                                       -- Creating a note from within Downloads will create this folder, 
           zettelkasten/
                daily/
                weekly/
                templates/
    Pictures/
    Videos/
    zettelkasten/                          -- User created folder
        daily/
        weekly/
        templates/                         -- User defined templates are in here
        ~/                                       -- Creating a note from within zettelkasten/ will create this folder, 
            zettelkasten/
                daily/
                weekly/
                templates/
            ~/                                   -- Creating a note from within zettelkasten/~/zettelkasten/ will create this folder, 
                zettelkasten/
                    daily/
                    weekly/
                    templates/
```

The solution is the specify the paths as `home="/user/name/zettelkasten"`, which both solves the problem of creating these subfolders and detecting the templates. If this bug cannot be resolved, at least the documentation should instruct the user to use `home="/user/name/zettelkasten". The current examples in `:h Telekasten` and the readme does not work (in all cases).
