### ISSUE TITLE
[BUG] default register for YankLink()

### ISSUE THREAD

**Issue by cnshsliu** [renerocksai/telekasten.nvim#229]
**Please confirm**
- [ ] I am running the latest version of this plugin

**Describe the bug**
YankLink does not put text into default register
 
**To Reproduce**
1. Start nvim
2. open a TK note
3. `:lua require('telekasten').yank_notelink()`
4. goto another buffer
5. press `p`

**Expected behavior**
`[[note_title]]` should be pasted

**Screenshots**

**Operating system (please complete the following information):**

**Additional context**
In `lua/telekasten.lua' line 1687
 `vim.fn.setreg('"', title)`
should be changed to
 `vim.fn.setreg('*', title)`

**Comment by cnshsliu** [comment]
In lua/telekasten.lua line 1687 
`vim.fn.setreg('"', title)`
should be changed to
`vim.fn.setreg('*', title)`

**Comment by lambtho12** [comment]
I am not sure about your setup, but it works as expected on my side and your proposed fix break it.
The code of this function has been untouched for more than two years now, so I am fairly certain it is not the culprit (people would have complained sooner).
Can you check on your side a bit more?

**Comment by cnshsliu** [comment]
My fault, my config uses `"*` as the source of `p` command.    `""p` works. sorry for being bothering.

**Comment by lambtho12** [comment]
All right then, glad you sorted it out!
