### ISSUE TITLE
[BUG] UUID is not set when goto today or goto weekly and create new entry.

### ISSUE THREAD

**Issue by rolfst** [renerocksai/telekasten.nvim#231]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**
I select either the entries goto today or goto thisweek to create a new entry. I get an error and an entry is created without the use of a template.

**To Reproduce**
1. Start nvim
2. open Telekasten panel
3. select either: goto today or goto thisweek (make sure no file for this was created previously)
4. select file (Note: no template is to be shown in preview pane)
5. press enter
6. See error
```
E5108: Error executing lua ...local/share/nvim/lazy/telekasten.nvim/lua/telekasten.lua:648: bad argument #2 to 'gsub' (string/function/table expected)
stack traceback:
        [C]: in function 'gsub'
        ...local/share/nvim/lazy/telekasten.nvim/lua/telekasten.lua:648: in function 'linesubst'
        ...local/share/nvim/lazy/telekasten.nvim/lua/telekasten.lua:673: in function 'create_note_from_template'
        ...local/share/nvim/lazy/telekasten.nvim/lua/telekasten.lua:1762: in function 'GotoDate'
        ...local/share/nvim/lazy/telekasten.nvim/lua/telekasten.lua:1821: in function 'selection'
        ...local/share/nvim/lazy/telekasten.nvim/lua/telekasten.lua:3131: in function 'panel'
```

**Expected behavior**
Upon selection of file i expect the template content to be displayed in the preview pane, and on enter I expect no error and a file created based on the template.

**Operating system (please complete the following information):**
 - OS: ubuntu 22.04

**Additional context**
neovim v0.9.0-dev

**Comment by lambtho12** [comment]
Works as expected on my setup. Can you post your config? Especially the part were you setup the different directories?

**Comment by rolfst** [comment]
sure, here goes:
```
local home = vim.fn.expand("~/notes")
zettelkasten.setup({
    home = home,
    filename_space_subst = "_",
    command_palette_theme = "window",
    show_tags_theme = "window",
    media_previewer = "viu-previewer",
    dailies = home .. "/" .. "dailies",
    weeklies = home .. "/" .. "weeklies",
    templates = home .. "/" .. "templates", -- path to templates
    template_new_note = home .. "/templates/new_note.md",
    template_new_daily = home .. "/templates/daily.md",
    template_new_weekly = home .. "/templates/weekly.md",
})
```

if I goto to the functions I see the place with uuid is filled with a `'_'`.
```
local function GotoDate(opts)
    opts.dates = calculate_dates(opts.date_table)
    opts.insert_after_inserting = opts.insert_after_inserting
        or M.Cfg.insert_after_inserting
    opts.close_after_yanking = opts.close_after_yanking
        or M.Cfg.close_after_yanking
    opts.journal_auto_open = opts.journal_auto_open or M.Cfg.journal_auto_open

    local word = opts.date or os.date(dateformats.date)

    local fname = M.Cfg.dailies .. "/" .. word .. M.Cfg.extension
    local fexists = file_exists(fname)
    if
        (fexists ~= true)
        and (
        (opts.dailies_create_nonexisting == true)
        or M.Cfg.dailies_create_nonexisting == true
        )
    then
        create_note_from_template(
            word,
            _,
            fname,
            M.note_type_templates.daily,
            opts.dates
        )
        opts.erase = true
        opts.erase_file = fname
    end
```
when I change this to:
local function GotoDate(opts)
```
.
.
.
    if
        (fexists ~= true)
        and (
        (opts.dailies_create_nonexisting == true)
        or M.Cfg.dailies_create_nonexisting == true
        )
    then
        local uuid = get_uuid(opts)
        create_note_from_template(
            word,
            uuid,
            fname,
            M.note_type_templates.daily,
            opts.dates
        )
        opts.erase = true
        opts.erase_file = fname
    end
```
it does work. so far.

**Comment by lambtho12** [comment]
I think I understand the issue now....
Correct me if I am wrong, but basically you have at some point `{{uuid}}` in your template for daily/weekly notes, right?

As it is currently implemented, the UUID system is mostly meant to prefix/replace the filename for regular notes. This is because in zettelkasten, you never know if the title of a note will change, hence UUID makes more sense to keep all links working when changing a note title.
Daily/weeklies are special notes that have their own naming format. This is done so other functions can differentiate straight away between a note and a journal entry. See `:h telekasten.note_naming`. Because of that, these special notes do not use uuid at all. Therefore, calling it from their template leads to the issue. 

Can you confirm I got all this right and expand a bit more on your workflow/usecase for a UUID in these notes?

If the goal is just to have a datetime stamp, just use the proper template for that instead of `{{uuid}}`. If you really want an unique identifier for all your notes, then yes the fix you propose will likely solve that, I can review it a bit more in depth and push it.

**Comment by rolfst** [comment]
none of my templates  show `{{uuid}}`. these are my templates:
daily: 
```
    ---
    title: {{hdate}}
    ---
```
weekly: 
```
    ---
    title: {{year}}-W{{week}}
    date:  {{hdate}}
    ---
    # Review Week {{week}} / {{year}}
```
basic (new_notes):
```
    ---
    title: {{title}}
    date:  {{date}}
    ---
```
I wanted to use `{{uuid}}` in te titles but I got a failure so I hold back of those.

**Comment by rolfst** [comment]
what I do notice in when I print the value of uuid in this function:
```
local function linesubst(line, title, dates, uuid)
    if dates == nil then
        dates = calculate_dates()
    end
    if uuid == nil then
        uuid = ""
    end
...
```
When I print uuid I see it as `<userdata 1>` not at `nil`

**Comment by narodo** [comment]
I have the same issue. 
I don't use {{uuid}} in any of my templates either.

**Comment by Inom-Turdikulov** [comment]
After some update, I have this issue too.
```
E5108: Error executing lua: ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:649: bad argument #2 to 'gsub' (string/function/table expected)   
stack traceback:
        [C]: in function 'gsub'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:649: in function 'linesubst'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:673: in function 'create_note_from_template'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:1761: in function 'GotoDate'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:1820: in function 'goto_today'
        .../after/plugin/telekasten.lua:25: in function <.../nvim/after/plugin/telekasten.lua:25>
``

**Comment by crbednarz** [comment]
I created a PR #238 which I believe should correct the issue.

In my environment at least, it appears `_` has a boolean value assigned to it. So when `_` is passed as the uuid, the code is expecting nil and instead receives a bool, causing the substitution to fail. Changing those calls to use `nil` explicitly seems to fix everything.
