### ISSUE TITLE
[BUG] Renaming file, links updated incorrectly if the files have similar names

### ISSUE THREAD

**Issue by dmytrodubinin** [renerocksai/telekasten.nvim#237]
**Please confirm**
- [x] I am running the latest version of this plugin

**Description:**
When we change the name of a file, the links to it must be updated. But there is a problem. If in the links we have addresses to files whose names are similar to the file that we are renaming, then all links are updated even if they do not lead to the original file.
The easiest way to explain this is with a video example.
[Screencast from 2023-03-29 17-14-43.webm](https://user-images.githubusercontent.com/8066458/228567546-8300f578-4d74-43e9-9558-54c89820a51a.webm)

On the demo you can see how I have 2 links, one of them to the original file, the other to another file with a similar name. After the update, both links were updated, although only one link should have changed
In my opinion, this is a serious bug, since it corrupts all links to files with a similar name, which is extremely difficult to trace in the future.

**Operating system (please complete the following information):**
 - OS: Arch Linux

**Comment by lambtho12** [comment]
This is indeed a big issue that should be easy to fix.
I will look at it right away.
