### ISSUE TITLE
[BUG] attempt to index local 'ret' when image_subdir is not set

### ISSUE THREAD

**Issue by jonasrogert** [renerocksai/telekasten.nvim#244]
**Please confirm**
- [ X] I am running the latest version of this plugin

**Describe the bug**
I get this error on startup:

```
Error detected while processing dotfiles/config/nvim/plugin/telekasten.lua:
E5113: Error while calling lua chunk: ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:239: attempt to index local 'ret' (a nil value)
stack traceback:
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:239: in function 'make_config_path_absolute'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:2781: in function 'Setup'
        ...ite/pack/packer/start/telekasten.nvim/lua/telekasten.lua:2812: in function 'setup'
        dotfiles/config/nvim/plugin/telekasten.lua:3: in main chunk
```

**To Reproduce**
1. Start nvim
2. See error

**Expected behavior**
If i set `image_subdir` to something (i set it to same as home) in the setup everything works. like this:

```
home = vim.fn.expand("~/Documents/notes")
require('telekasten').setup({
    home = home, -- Put the name of your notes directory here
    image_subdir = home,
})
```

**Operating system (please complete the following information):**
 - OS: Linux

**Additional context**
I don't use images so i haven't tested if it stops working after setting the image_subdir.

Thanks for a great plugin! I use it all the time!

**Comment by lambtho12** [comment]
Are you sure you are running the absolute latest version ? I pushed a few patches to this function specifically over the last few days.
