### ISSUE TITLE
[FR] Combine oldfiles and find_notes

### ISSUE THREAD

**Issue by thw26** [renerocksai/telekasten.nvim#250]
**Please confirm**
- [x] I am running the latest version of this plugin

**Is your feature request related to a problem? Please describe.**
Telescope includes a command, `oldfiles`, which shows recently modified files. Telekasten has a `fine_notes` but not an `oldfiles` implementation.

**Describe the solution you'd like**
Instead of providing a mere wrapper for `oldfiles`, Telekasten could provide its `find_notes` menu with a combination of `oldfiles` and `find_notes`. This might look like providing the list of most recent files on loading the menu but then on typing begin narrowing down the options across the whole vault.

**Describe alternatives you've considered**
The obvious alternative is to maintain two keybindings or make a menu popup like described below.

**Additional context**
I thought of this while writing a `nui` popup. The popup was meant to simplify keybindings by allowing me to use a single binding to then select either `new_note` or `new_templated_note`. (I bound this to <C-N> for ease of access.)

Right now I need two bindings for finding my files: one for `find_notes` and one for `oldfiles`. Searching `oldfiles` only searches the `oldfiles` list and not the entire vault. The thought is, if want to find a file, I most likely either want a recent file and thus should be presented with it, and if I actually do want a different file, I will need to FZF for it anyways.

This is similar to the way Obsidian handles this: when you hit `<C-O>`, you get an FZF menu with suggestions. The immediate suggestions are the X most recent files.

**Comment by lambtho12** [comment]
Is this similar to setting the `sort='modified'` option?

Altough we could probably also change [line 1648](https://github.com/renerocksai/telekasten.nvim/blob/8a8daa0ea1b288011f2118155b5620ec3cfc4ec6/lua/telekasten.lua#LL1648C28-L1648C28), in order to allow option to be passd to the FindNote command directly. This way you could make different mappings if you want different sorting options to be available simultaneously.

**Comment by thw26** [comment]
I think this would be like `sort="modified"` but I can't tell if this option is working. I have this in my init.lua. FWIW, I'm using LazyVim.

```
  require("telekasten").setup({
    home = vim.fn.expand("~/Documents"),
    templates = vim.fn.expand("~/Templates"),
    image_subdir = nil,
    extension = ".md",
    new_note_filename = "title",
    uuid_type = "%H%m%d",
    filename_space_subst = "_",
    image_link_style = "wiki",
    tag_notation = "@tag",
    sort = "modified",
```

But when I then run `:Telekasten find_notes`, the file picker isn't returning the most recently modified files nor on typing does it appear to do so. As an example, I have a directory called `Quotes` in which I store the various quotes I find as I research. When I type `Quotes` into the picker to narrow down to that directory, I am returned the list of files but the first quote (pressing `<UP>`) and the last quote (pressing `<DOWN>`) are not the most recently added quote file.

Setting this option in `/plugins/telekasten.lua` shows no difference. Removing `sort = "modified",` results in no change in the picker's results when typing or the files suggested on open. (Perhaps I am misunderstanding what `sort="modified"` is supposed to do.)

The thought of this FR is, on opening the file picker (I've mapped this to <leader>ff) that the most recent files (i.e., list from `oldfiles`) are offered with nothing yet typed, but as soon as you start typing, the normal FZF functionality takes over (and I suppose the most recently modified files would be the closest to the prompt). I hope this helps clarify what I meant.

**Comment by lambtho12** [comment]
> The thought of this FR is, on opening the file picker (I've mapped this to ff) that the most recent files (i.e., list from oldfiles) are offered with nothing yet typed, but as soon as you start typing, the normal FZF functionality takes over (and I suppose the most recently modified files would be the closest to the prompt). I hope this helps clarify what I meant.

Yes this was my understanding. I have never used the `sort = 'modified'` option myself, so I am not really sure about how it works.
I will look into both `oldfiles` and our sorter implementation into more detail. Maybe something is not working as expected here.

**Comment by thw26** [comment]
This plugin accomplishes what I am looking for: https://github.com/prochri/telescope-all-recent.nvim

Should we keep this open until we investigate why `sort = 'modified'` doesn't work as expected?
