### ISSUE TITLE
[BUG] Switching Vaults Does Not Change Root Directory for Finding Notes

### ISSUE THREAD

**Issue by thw26** [renerocksai/telekasten.nvim#255]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**
After using `:Telekasten switch_vault`, find files does not recognize the change in root directory.

**To Reproduce**
Here is my config:

```
home = vim.fn.expand("~/Documents"),                                 
vaults = {                                                           
  DirX = {                                                     
│ │ home = "~/.local/share/Cryptomator/mnt/DirX/",
│ │ templates = vim.fn.expand("~/Templates"),                        
│ │ image_subdir = nil,                                              
│ │ extension = ".md",                                               
│ │ new_note_filename = "title",                                     
│ │ uuid_type = "%H%m%d",                                            
│ │ filename_space_subst = "_",                                      
│ │ image_link_style = "wiki",                                       
│ │ tag_notation = "@tag",                                           
  },                                                                 
},                                                                   
templates = vim.fn.expand("~/Templates"),                            
image_subdir = nil,                                                  
extension = ".md",                                                   
new_note_filename = "title",                                         
uuid_type = "%H%m%d",                                                
filename_space_subst = "_",                                          
image_link_style = "wiki",
tag_notation = "@tag",
```

1. When I issue `Telekasten switch_vaults` and I change to DirX, the note finding picker can't find my files.
2. When I issue `Telekasten find_notes`, the picker continues to show files found in the default home dir, not for DirX

**Expected behavior**
When switching vaults, the note finder should switch root directory in which it is searching for notes.

**Screenshots**

**Operating system (please complete the following information):**

**Additional context**
Is this perhaps some bug with the hidden directory of `.local`?

I tried opening nvim from my home dir (`~`) and it returned results from other locations (e.g., `~/Downloads`) but it would not return results from `.local`.

**Comment by lambtho12** [comment]
Can you try with a full path instead of `~` for home? This might be the issue.

Like `home = vim.fn.expand("~/.local/share/Cryptomator/mnt/DirX/")`

**Comment by thw26** [comment]
No change in behavior when I swapped `~` for the full path.

**Comment by thw26** [comment]
Interesting! I think I got a good clue here.

I normally initiate `find_notes` through the keybinding above.

When I run it manually by typing `:Telekasten find_notes`, the vault switch is recognized, albeit it isn't seeing all the files, but only two markdown files at the top of the directory. Making it a git repo causes it still to only see the top two files.
