### ISSUE TITLE
[FR] support for normal markdown link syntax

### ISSUE THREAD

**Issue by Aneeqasif** [renerocksai/telekasten.nvim#258]
currently the way to link and search for backlinks is to use [[hello]] style but my other plugin that i use to preview markdown do not detect it as link syntax , it will be really nice to select the type of links a person needs , as it will make it easy to work  with other plugins that expect a standard or (different then current) style of linking, 
i hope u get my point , not good at writting in english
thanks in advance.

**Comment by lambtho12** [comment]
Duplicate of #126
