### ISSUE TITLE
[BUG] Cannot create a new note with a subdirectory if the subdirectory does not exist

### ISSUE THREAD

**Issue by Sleepful** [renerocksai/telekasten.nvim#266]
First off, I just installed this plugin and the features are blowing me away. Thank you!

**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**

Create new note, the `title` prompt comes up, add something with a subdirectory like `subdir/hello`, if `subdir` does not exist then error pops up

**Expected behavior**
It would be nice if the `subdir` is created correctly when creating a new note

**Operating system (please complete the following information):**
 - OSX

**Comment by wqk151** [comment]
I use your fork, the feature is great, thanks
