### ISSUE TITLE
[BUG] Minor errors in the docs

### ISSUE THREAD

**Issue by Dioprz** [renerocksai/telekasten.nvim#273]
**Please confirm**

- [x] I am running the latest version of this plugin

**Describe the bug**

Hello,

Some hours ago I was learning how to properly config telekasten, and reading the docs I find some minor errors that I want to report:

In the README:

1. Usage -> Commands -> panel : This link sends to a non-existant file.

In the docs (:h telakesten):

1. *tag_notation* don't have any references to the '@tag' notation.
2.  *setup()* may have text in the wrong place (line 128).
```
      -- Tag list theme:
        -- get_cursor: small tag list at cursor; ivy and dropdown like above
      show_tags_theme = "ivy",
```
3. *setup()* also don't have any references to the '@tag' notation.
4. *setup()* line 431. There are **three** options.

Thank you so much for your plugin, your documentation was excellent, and allowed me to set up and understand everything in just a couple of hours!

**Comment by lambtho12** [comment]
Thank you for pointing all this out. I will fix it ASAP

**Comment by lambtho12** [comment]
Not sure about your points 1 and 3. Aren't they the same? Did I forgot something in 70a01f8?

**Comment by Dioprz** [comment]
Sorry, they do look the same, but I was referring to the following:

1. when running `:h telekasten.tag_notation`, the documentation had no reference to the `@tag` notation. 

3. When running `:h telekasten.setup()`, the documentation also has a small aside regarding supported notations, and that documentation does not include `@tag`.

Reviewing the commit, I think that the correction of item 3 is missing?

Again, thank you very much!

**Comment by lambtho12** [comment]
Should be all good now. If you find other stuff, do not hesitate to report. Any contribution helps.

Thank you very much.
