### ISSUE TITLE
Modify telekasten's panel?

### ISSUE THREAD

**Issue by rhaynes74** [renerocksai/telekasten.nvim#292]
**Please confirm**
- [ X] I am running the latest version of this plugin

**Tell us about what's bothering you...**
... How do I go about modifying Telekasten's panel? I want to simply the number of options.

**Comment by lambtho12** [comment]
The panel cannot be modified. Just type what you are a looking for and the list will reduce fairly quickly. This is way faster than navigating up/down anyway. 

This original workflow imagined when implementing this panel was that the user would have key mappings for most telekasten functions. Most of these mappings will be of the form `<leader>` + telekasten prefix + function prefix. Example: `<leader>zf` could mean "zettel find" (=find a note), etc. 
The intended workflow is to have the panel mapped with `<leader>z`, so if you cannot remember the specific function mapping quick enough, nvim will show the panel and you can pick from that. If you use a dedicated mapping plugin (such as `folke/which-key.nvim`), then the panel is a bit redundant and can completely be left out in my opinion. If you still want only a small subset of options, I would use which-key and tweak it as you see fit, but it does not work quite exactly like telekasten panel.

I hope this shed a bit of light on the intended use of the panel and the reason why it is not customizable and will not be developed to be.

**Comment by rhaynes74** [comment]
Many thanks for taking the time to respond!
