### ISSUE TITLE
How to automatically generate block ids?

### ISSUE THREAD

**Issue by MarcoCamilo** [renerocksai/telekasten.nvim#307]
I'm trying / waiting to find a nvim tool that can replace LogSeq (at least including the vital features like backlines, transclusion and block references). With regards to this last one, I think telekasten is the only tool that comes close right now (and maybe only a few steps towards actually being a replacement!)

But I wanted to ask how can block ids be generated automatically? This is referred in the wiki, but there's no reference to alternatives on how to automatically manage block ids. Any references for such a tool?

**Comment by lambtho12** [comment]
I do not really understand what you want. Can you give an example? 
What is a _block reference_ or _block id_? What do you mean by _manage block id_?

**Comment by MarcoCamilo** [comment]
Read the documentation section “Notation” and read this. The block id is a unique identifier for a block of text.

After that you’ll understand my question.

Marco-Andrés Camilo-Pietri

**Comment by MarcoCamilo** [comment]
Didn’t know you were a maintainer, plus I thought you’d be familiar with the [documentation](https://github.com/renerocksai/telekasten.nvim/wiki/Notations#paragraph-links), which is clear about this. No worries.

Block ids are the unique identifiers the plugin reads to reference paragraphs within a note (also called block references in note-taking). For example:

- [[A cool title#^xxxxxxxx]]  ....... links to the paragraph with id ^xxxxxxxx within the note named 'A cool title'

The documentation mentions “typically, block ids are tool-generated”. Thus, my question is: how? I’m cleaning telekasten doesn’t do this right now, but if the creator/maintainer has an idea of what kind of tools can generate these block ids.

**Comment by renerocksai** [comment]
Done, wiki is off. Thx for the hint. Also, the uuid function is a good suggestion!

**Comment by renerocksai** [comment]
> I am currently the sole maintainer of Telekasten. I am overworked like crazy and do not have time to play games to decipher what people have in mind.

@lambtho12 
Same here. Will mail you at some time. Starting a new job (at startup) on Fri so no idea when. Basic idea: let's move to gh organization and prominently ask for new maintainer in readme. Discord server could be set up by new maintainer, as I have no attention span left for online chat.
