### ISSUE TITLE
[Bug] Drodown panel display issue 

### ISSUE THREAD

**Issue by lambtho12** [renerocksai/telekasten.nvim#31]
I tried setting  `command_palette_theme = "dropdown"`, but it does not have the same layout as yours (see below)

![Screenshot 2021-12-10 at 13 46 14](https://user-images.githubusercontent.com/26206736/145576343-ac82a535-fca0-485f-b41d-3adca786c055.png).

I guess the problem comes from my telescope config, which has a `prompt_position=bottom` as default (which I like more for "normal" telescope popup)

```lua
    layout_config = {
      width = 0.75,
      preview_cutoff = 120,
      prompt_position = "bottom",
      horizontal = {
        mirror = false,
        preview_width = 0.5,
      },
      vertical = {
        mirror = false,
      },
    },
```

Maybe you need to set explicitly the `layout_config` for the command panel to ensure it looks as expected.

BTW, in readme you mention multiple times "popup" theme, but in the config example you say "dropdown". [In the end it does not matter](https://www.youtube.com/watch?v=eVTXPUF4Oz4) as this theme is [the fallback one in the config](https://github.com/renerocksai/telekasten.nvim/blob/c5fb4f7f282489e601d78a55fd4d81d381a65c53/lua/telekasten.lua#L1653-L1657), but it could be nice to have a single name for it.

**Comment by renerocksai** [comment]
Thanks for bringing this up and paying attention to the docs!

**Comment by lambtho12** [comment]
If I knew the fix was that simple, I would have done it myself :sweat_smile:
