### ISSUE TITLE
[FR] Choose clipboard manager provider

### ISSUE THREAD

**Issue by andy941** [renerocksai/telekasten.nvim#320]
**Please confirm**
- [ x] I am running the latest version of this plugin

**Is your feature request related to a problem? Please describe.**
On my system (Manjaro i3), xsel does not seem to work properly, I primarily use xclip. In the [telekasten logic](https://github.com/renerocksai/telekasten.nvim/blob/39c7945d6d209ab921c0ea2b9328d5627e66a6f4/lua/telekasten.lua#L375) the order with which clipboard providers are chosen is arbitrary and hard-coded. Would it be possible to add a flag to override the behaviour? When I force xclip to be used the image pasting works like a charm. Being able to paste images is kind of a deal-breaker for me.

Thank you for the great plugin!
Andrea

**Comment by lambtho12** [comment]
Yeah. I am not really a fan of the current logic either, but while testing it did not seem to have any issue on my end, so I assumed that it was good enough.

We could indeed add an option to select explicitly between `xsel` or `xclip`. This would be a very simple change and good first issue to tackle. Do you want to have a shot at it? I will gladly review and merge the PR for that.
