### ISSUE TITLE
[BUG] Find daily notes & find week notes both show all the notes

### ISSUE THREAD

**Issue by marad** [renerocksai/telekasten.nvim#321]
**Please confirm**
- [X] I am running the latest version of this plugin

**Describe the bug**
Both finding daily and weekly notes show all the notes that I have in my notes folder.

**To Reproduce**
1. Start nvim
2. :Telekasten find_daily_notes  (or :Telekasten find_weekly_notes)
3. Telescope window shows all the notes

**Expected behavior**
I'd like to only see daily/weekly notes

**Screenshots**

**Operating system (please complete the following information):**
 - OS: Ubuntu 22-04

**Additional context**

**Comment by Tonitum** [comment]
Do you have the daily/weekly folders set to a different directory than the home directory? As far as I can tell, the pickers launched by find_daily_notes/find_weekly_notes uses the configured folder as the cwd for telescope.

**Comment by marad** [comment]
@Tonitum No, I have everything laying flat within the `~/notes' folder. Should daily/weekly notes be in some specific place? When I create a daily note it also creates it within the '~/notes` folder.

**Comment by lambtho12** [comment]
Then it is normal. 

Basically `find_daily/weekly` opens a picker in the configured `dailies` and `weeklies` directory. If you have not specified anything special, it will always return everything in your home.

**Comment by lambtho12** [comment]
Not sure if there is a fix for that to be honest.

If it is possible, we could ask ripgrep to only search in files with the appropriate filename convention rather than using the default `find_command`. But I am not sure if it is possible.

**Comment by Tonitum** [comment]
Yeah, I can take a crack at this!

**Comment by Tonitum** [comment]
Think this is resolved, PR is here: https://github.com/renerocksai/telekasten.nvim/pull/328
