### ISSUE TITLE
[BUG] nvim_win_set_cursor error when using telescope pickers

### ISSUE THREAD

**Issue by viniciusmiradouro** [renerocksai/telekasten.nvim#327]
**Please confirm**
- [X] I am running the latest version of this plugin

**Describe the bug**

Whenever I try to use any plugin picker I get the following error and the file list has errors rendering:

`Error executing vim.schedule lua callback: ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:1467: Cursor position outside buffer
stack traceback:
	[C]: in function 'nvim_win_set_cursor'
	...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:1467: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>`

**To Reproduce**
1. Install LazyVim
2. Install Telekasten
3. Start nvim on a note in a vault with other notes
4. Run `:Telekasten`
5. Select `insert link`
6. Try searching for a note to link
7. See error

**Expected behavior**
The error message above appears as text is added to the search bar, also, as the note list narrows, the list does not render properly.

**Screenshots**

**Operating system (please complete the following information):**
 - OS: Arch Linux

**Additional context**
Already tried looking for issues on the Telescope and LazyVim repos related to the error and found nothing. When using pickers not related to Telekasten (such as find_files) everything works normally.

**Comment by lambtho12** [comment]
I cannot reproduce. The function works just fine for me and the link is inserted properly. Could you investigate a bit more so I can look for how to fix it?

**Comment by viniciusmiradouro** [comment]
Tried to investigate a bit more but found nothing. When I follow the steps above it is completely reproducible on my machine. Maybe the problem is the lua on my path or something of the sort. But everything seems to be up to date... Strange.

**Comment by viniciusmiradouro** [comment]
Found it. In my vault I had files terminating with `^J.md` (Like `Hipérbola^J.md`), which obviously caused problems in the code execution. After I deleted them, it went back to normal. So not a bug after all, I guess.

**Comment by lambtho12** [comment]
Gosh were do you people get such filenames :smiley: I would have never guessed it in a million years.
I am glad you found out!

Although, we could probably try to properly sanitize everything we put in regex in order to minimize these kind of issues...

**Comment by viniciusmiradouro** [comment]
I developed a program to help me manage large amounts of study materials (kinda like incremental reading) that creates notes via rofi in my vault. This way I can use the linking capabilities of telekasten to form a web o knowledge. The problem is that the name picker on rofi was outputing an "\n" at the end of the names and that was converted to `^J` somehow, lol.
