### ISSUE TITLE
Add follow_date() picker for journal entries

### ISSUE THREAD

**Issue by lambtho12** [renerocksai/telekasten.nvim#45]
If the journal is not a subdirectory of the home zettelkasten, it is not possible to use follow_link() to open a link to a daily/weekly note, as follow_link() looks for files in the ZK home directory.

A new picker should therefore be created to open journal entries. Note that, as the filename format of the journal entries is hardcoded, a single picker could be implemented. The picker would parse the link and determine whether it has to look inside the dailies or weeklies directory.

**Comment by renerocksai** [comment]
That is only partly true. `resolve_link()` will find the note; it is just that later when the picker is called, the ZK home is passed to the picker, based on the assumption that it applies to all notes.

The plugin just was not made for journals that don't share a common root. 

I don't think a new picker would be a good solution. Instead, `resolve_link()` should return the root dir it found the note in: home, dailies, weeklies - and pass that on to the picker.

**Comment by renerocksai** [comment]
Just some additional info: Currently, there is no way for telescope to look in 2 or more unrelated folders. If the dailies and weeklies would be unrelated and you would call the new picker, that could be a problem: what `cwd` to pass in? So a simple picker might not have cut it anyway - one would have `scan_dir()`ed both dailies and weeklies and used a table picker instead.

Anyway: the `find_daily_notes()` and `find_weekly_notes()` can be used to insert links in such a setup - and with a patch to `follow_link()`, everything should work.

**Comment by lambtho12** [comment]
Ah yes, I didn't check `resolve_link`. A simple patch to `follow_link()` should be more than enough.

Yes I use find_daily_notes() already, all is good with this one.

I stumbled across this issue because I added links to prevday and nextday in the template of my daily notes so I can easily access these when editing a specific note, and I was not able to follow_link() to open them.

**Comment by renerocksai** [comment]
That should be fixed soon. 

However, as I mentioned elsewhere (PR #44 ) I think: This won't fix being unable to `search_notes()` or search for tags in directories outside of the ZK home. We would have to implement a is-not-related detection and find a way to grep in multiple directories for `search_notes()` - and also search for tags in multiple directories.

I think a smarter option might be: putting symbolic links to your journal into your ZK home.

**Comment by renerocksai** [comment]
```console
$ zkh= YOUR ZK HOME
$ journal= YOUR JOURNAL DIR
$ cd $zkh
$ ln -s $journal journal_notes
```

And then configure the `journal_notes` subdir as `daily` (and `weekly`) directory.

**Comment by lambtho12** [comment]
> I think a smarter option might be: putting symbolic links to your journal into your ZK home.

Definitely! I did not thought of that before 😅. I will do it right away.

**Comment by renerocksai** [comment]
In addition, I just implemented the fix discussed above :smile:
