### ISSUE TITLE
When inserting image from clipboard telekasten doesn't save the image into subfolder. 

### ISSUE THREAD

**Issue by z-w-v** [renerocksai/telekasten.nvim#48]
I was trying out telekasten and found out that when pasting image from clipboard it doesn't save it into subfolder (in my case "img"). 
I tried to find what could cause this and found out that telekasten doesn't update the `pngpath` variable if there is `image_subdir` set in the config.

It seems that configuring the function `imgFromClipboard()` fixes this issue:
```    
    if M.Cfg.image_subdir then
        relpath = M.Cfg.image_subdir .. "/" .. pngname
	pngpath = M.Cfg.home .. "/" .. M.Cfg.image_subdir
    end
```

**Comment by renerocksai** [comment]
Thanks for reporting this! There is obviously something wrong here.  It seems like I must have forgotten to use the
relative path for the actual work - not just for the link!

Will fix it asap!

**Comment by renerocksai** [comment]
BTW your fix looks correct. I just tried to not look at it and came up with the same. So I'll forego testing and just "ship it" :smile:
