### ISSUE TITLE
Please provide template variable for RFC3339 date format

### ISSUE THREAD

**Issue by zalegrala** [renerocksai/telekasten.nvim#61]
Another tool I'm using to read these notes operates on dates with RFC3339 formatting.  It wold be handy to have such a template variable to use for this purpose.

**Comment by zalegrala** [comment]
Nice, that looks reasonable to me.

**Comment by renerocksai** [comment]
I just reviewed the PR and it needs a tiny bit of work to also support the use-case of creating a daily note via the calendar. So it needs to support dates from the past and future.

**Comment by lambtho12** [comment]
@zalegrala , RFC3339 needs hours, minutes and seconds. The change proposed by @renerocksai  and implemented in https://github.com/renerocksai/telekasten.nvim/pull/62/commits/9ad4bfa59cae6e0dfb065bdfcdc9e42922d16fba will always use the time of creation of the note for hours and minutes even if the note if for a past date. Example, on `2022-01-16T8:44Z+01:00` I create a note for last week. This will lead to `2022-01-09T8:44Z+01:00`. To me, this is not really a big deal. Do you think it is ok as well? Or do you envision a case where it could cause issues? If it could be of any issue, I think it should set a default time for notes related to other days (`T00:00:00Z<your current timezone>` for instance).
