### ISSUE TITLE
Add templates for issues, requests, PR, etc.

### ISSUE THREAD

**Issue by lambtho12** [renerocksai/telekasten.nvim#66]
As proven in #65 , people (me) tend to forget some trivial stuff from time to time, such as adding documentation for their feature.

I think it would be good to have a template (at least for PR) with a checklist to ensure changes of good quality. Such checks would ensure that `README` and `doc/telekasten.txt` were updated if necessary, that the code was styled with sylua following the config provided, etc.

A very complete template that I like is [the one from home-assistant](https://github.com/home-assistant/core/blob/dev/.github/PULL_REQUEST_TEMPLATE.md), maybe we could draw inspiration from that...

**Comment by renerocksai** [comment]
I hate bureaucracy! And since this is rather a niche plugin, I want to keep the hurdles low. 

But I'll check out your link! It is for the better after all! And it makes sense. Maybe ppl appreciate it. Who knows...

**Comment by lambtho12** [comment]
I am not fond of bureaucracy either, but I like to be reminded of checking everything before doing a PR. :smile: 
So indeed, there is no need to be too rigid here, a small todo list is plenty enough. The template could also be just some comments that will not even be displayed, just to act as a reminder.

**Comment by renerocksai** [comment]
OK, we have PR and issue templates now :smile: 

Thanks for all your valuable suggestions and contributions!
