### ISSUE TITLE
[BUG] Highlights not showing in file, but show in highlight test

### ISSUE THREAD

**Issue by nucleogenesis** [renerocksai/telekasten.nvim#72]
**Please confirm**
- [x] I am running the latest version of this plugin 

**Describe the bug**

I just installed today using `vim-plug`. 

I have added the color configs into my init but I do not see them when I open my daily note and add a tag, link or highlight.

![image](https://user-images.githubusercontent.com/6356129/150233719-08396b5f-c29d-4f4c-849f-7b396703d6b6.png)

However, running `:so $VIMRUNTIME/syntax/hitest.vim` shows the colors as expected (right side is a daily note I made with the plugin):

![image](https://user-images.githubusercontent.com/6356129/150233366-fa9e41f1-1f2c-4b98-920c-05256055d726.png)

`echo &filetype` when in my daily note file returns `telekasten` as well.

Seems like everything should be in place but my tags and links don't show anything. Any help or even ideas on what I might look at to figure it out would be much appreciated.

I also tried adding the `hi` commands into a file and `:source`-ing it as noted here: https://github.com/renerocksai/telekasten.nvim/issues/54#issuecomment-1003801772

I also tried adding it to the end of the vim-colorschemes color file for the theme I'm using, then ran that theme to no effect.  I tried without any colorscheme called to no effect as well.

**To Reproduce**
- Run my setup? Not sure how easily this can be replicated, but [here is my init.vim](https://gist.github.com/nucleogenesis/f820ba5cb99f0cf8d09dd71422cbd142)

**Expected behavior**
Tags, highlights, links, etc appear based on the `hi` setting for their color group.

**Screenshots**
Posted above.

**Operating system (please complete the following information):**
 - Fedora 34
 - nvim 0.6.0
 - Alacritty & Terminator terminals were tested

**Additional context**
This looks awesome if I can get this worked out I'm really excited to try it out for a while.

**Comment by renerocksai** [comment]
Very strange. Usually, when you don't see highlights, it is because you are defining terminal colors (ctermfg=...) but use termguicolors which would require defining guifg=...

But that seems not to be the case.

I would recommend stripping your config to the bare minimum and try again. I don't know how much other plugins like vim-polyglot interfere with nvim's syntax highlighting.

**Comment by renerocksai** [comment]
Another thing you can try is testing with a different, neutral filename extension, like `.xxx` - and see if it works then. If yes, something is messing with markdown file syntax. When you (or the plugin) set the filetype to telekasten, the telekasten syntax file is loaded which inherits the "markdown" syntax. So anything interfering with this simple nvim syntax mechanism I would try to eliminate.

**Comment by nucleogenesis** [comment]
Much appreciated @renerocksai  - it was `vim-polyglot` - when I disabled the plugin or added this above the `Plug "vim-polyglot"` line:

`set g:polyglot_disabled = ["markdown"]`

It worked for the most part. I wasn't seeing the underline on links and opted to just try out [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) in place of vim-polyglot and now things look good overall.
