### ISSUE TITLE
[Wiki additions]

### ISSUE THREAD

**Issue by lambtho12** [renerocksai/telekasten.nvim#77]
Adding stuff to the wiki according to [this method](https://gist.github.com/larrybotha/10650410) (see https://github.com/renerocksai/telekasten.nvim/discussions/75#discussioncomment-2016096).

As the method says, 
1. I cloned the original repo's wiki
2. I made some changes and pushed them on my fork of this remote's wiki (lambtho12/telekasten.nvim.wiki.git)

To merge, you need to
1. Clone the original repo's wiki and `cd`into it
2. Pull my changes: `git pull git@github.com:lambtho12/telekasten.nvim.wiki.git`
3. Push to master

This issue only serves to notify you that new changes have been added to (my fork of) the wiki and need to be pulled.

**Comment by renerocksai** [comment]
Oh, thanks!!!!!!!!!!

Why can it not do PRs?

That seems bad since I can't keep track of all forks and whether they changed their wikis...... I bet there is a way.....

**Comment by renerocksai** [comment]
I've pushed it :smile:

**Comment by lambtho12** [comment]
@renerocksai 


> Why can it not do PRs?

Because Github (and Gitlab) both consider Wikis as small stuff that only the lead devs should touch it seems. Even though they both implement Wikis as regular repositories. This is quite ridiculous as everyone in the communities are asking for the ability to use wikis as normal repositories...

> That seems bad since I can't keep track of all forks and whether they changed their wikis...... I bet there is a way.....

Yeah I do not quite like this workaround either, but there is not better way for Github/Gitlab wikis. People that are eventually fed-up with that often move to static site generator (hugo or readthedocs for instance), create a separate repo for their doc and have a pipeline to automatically build and publish the latest push. But this is quite cumbersome.


Anyway, I am going to complete the wiki today so I is up to date with the current status of the README and doc/

**Comment by renerocksai** [comment]
Thx for the wiki work! Well, for the time being, I can pull your stuff when you notify me. Isn't there a way to just fork the wiki repository? When you change from the wiki tab to the code tab?

**Comment by lambtho12** [comment]
> Isn't there a way to just fork the wiki repository? When you change from the wiki tab to the code tab?

Nope, no way to fork. What I had to do is:
1. Clone 'your' wiki
2. Create a blank wiki on my fork of the repo
3. Add an other remote to the clone of your wiki that points to the wiki of my fork
4. Do changes locally and push them on my fork (as I do not have writing right to 'your' wiki)
