### ISSUE TITLE
[BUG] error pulling in `wiki` submodule with fresh install

### ISSUE THREAD

**Issue by wimstefan** [renerocksai/telekasten.nvim#79]
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**
Updating telekasten.nvim with `PackerSync` throws an error on pulling in the wiki submodule.

**To Reproduce**
1. Install telekasten.nvim (in my case with `packer.nvim`)
2. Start nvim
3. Update packages with `PackerSync`
4. See error below
```lua
 ✗   Failed to update renerocksai/telekasten.nvim
  Errors:
    Already up to date.
    Cloning into '$HOME/.local/share/nvim/site/pack/packer/start/telekasten.nvim/wiki'...
    git@github.com: Permission denied (publickey).
    fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.
    fatal: clone of 'git@github.com:renerocksai/telekasten.nvim.wiki.git' into submodule path '$HOME/.local/share/nvim/site/pack/packer/start/telekasten.nvim/wiki' failed
    Failed to clone 'wiki'. Retry scheduled
    Cloning into '$HOME/.local/share/nvim/site/pack/packer/start/telekasten.nvim/wiki'...
    git@github.com: Permission denied (publickey).
    fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.
    fatal: clone of 'git@github.com:renerocksai/telekasten.nvim.wiki.git' into submodule path '$HOME/.local/share/nvim/site/pack/packer/start/telekasten.nvim/wiki' failed
    Failed to clone 'wiki' a second time, aborting
    fcfa869
```
**Expected behavior**
No errors on updating.

**Operating system (please complete the following information):**
 - OS: Gentoo Linux 

**Additional context**
 ```
NVIM v0.7.0-dev+913-ge07a4b97f
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by jglueckstein** [comment]
I had the same thing, using Packer.  However Packer is trying to handle the submodule requires you to have an SSH key added to your github account.  I think it's an issue with Packer.
Instructions are [here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh)

**Comment by renerocksai** [comment]
I second that. It seems to be an issue with the package manager trying to fetch the submodule. My experience with submodules is: don't touch them when they're working. I guess if I had added the submodule with an `https://` URL, this wouldn't have happened. However, I use SSH for pushing to repos and usually people fork and submit PRs....

I didn't even think about package managers trying to fetch the submodule. I'll try re-writing its origin...

**Comment by wimstefan** [comment]
That worked perfectly! Thanks for the fast fix 👍🙏
