### ISSUE TITLE
[FR] Sort options for find_notes

### ISSUE THREAD

**Issue by yutkat** [renerocksai/telekasten.nvim#85]
**Please confirm**
- [x] I am running the latest version of this plugin

**Is your feature request related to a problem? Please describe.**
I want to add a sort option to find_notes.

**Describe the solution you'd like**
```lua
require('telekasten').find_notes( {sort = { 'modified' }} )
```
sort options: title, created, modified

**Additional context**
In zk, sorting is implemented
https://github.com/mickael-menu/zk-nvim

**Comment by lambtho12** [comment]
I am not 100% sure, but it seems that this is considerably more difficult to do here than with zk. AFAIK, what zk-nvim does is that it calls zk with the sort option, and simply display what is returned (correct me if I am wrong).

Here we just pass everything to telescope and let it handle stuff. I am not sure telescope has the ability to sort stuff based on created or modified dates.

**Comment by lambtho12** [comment]
For reference, there is a plugin called [telescope-frecency](https://github.com/nvim-telescope/telescope-frecency.nvim). Maybe it could be nice to see if that can be added as a sort option at a later stage.
