### ISSUE TITLE
[FR] Option for `goto_today()` to jump straight to file

### ISSUE THREAD

**Issue by maxmahlke** [renerocksai/telekasten.nvim#93]
**Please confirm**
- [x] I am running the latest version of this plugin

**Is your feature request related to a problem? Please describe.**
When calling `goto_today()`, I always want to go to the markdown file of my note. Currently, I have to press enter in the telescope prompt. I would like to skip the telescope prompt altogether.

**Describe the solution you'd like**
Jump straight to the file instead of opening the telescope prompt.

**Describe alternatives you've considered**
I tried coming up with a mapping like

 `"<cmd>lua require('telekasten').goto_today()<CR><cmd>lua require('telescope.actions.set').select()<CR>"` 

but without success.

**Additional context**
It could be a boolean option like `jump_if_exists`, where if true you get the telescope prompt if today's note does not exist yet, and it jumps to the file if it exists already.

**Comment by lambtho12** [comment]
I agree, this would be a really nice feature.

We could even allow more customization by passing a list of pickers instead of boolean `jump_if_exists_list = {goto_today, follow_links}`, so it could also work with `follow_link()` for instance.

**Comment by Rom1deTroyes** [comment]
Same with `goto thisweek` !
:calendar:

**Comment by lambtho12** [comment]
Hey, just pushed a fix for this on branch https://github.com/renerocksai/telekasten.nvim/tree/93-fr-straight_jump

Could you try this?
Basically it introduces a global option `journal_auto_open` (default to false) that skips the prompt for `goto_today` and `goto_thisweek`.
I also made it so you can create special mappings if you do not want to change the default behavior.

```vim
nnoremap <leader>zT :lua require('telekasten').goto_today()<CR>
nnoremap <leader>zTT :lua require('telekasten').goto_today({journal_auto_open = true})<CR>
```

I think the same reasoning could be applied to other functions as well maybe, but I am not really sure if that would be really that useful. Do you have some opinions regarding that? Which functions then? Use a separate global setting like `journal_auto_open` and `note_auto_open`?

**Comment by maxmahlke** [comment]
Hi! I checked out the PR, it works as expected, nice work!

However, I'm no longer using this plugin, I switched to `vimwiki` for my dailies due to the integration with `taskwarrior` for the to-do list, and `zk` for the notes due to the command-line interface.

I'll give you my opinion anyway, I like the idea of the global `journal_auto_open` and `note_auto_open` settings. The user can then fine-tune the behaviour with the mappings as you showed.

**Comment by lambtho12** [comment]
Hey! Thank you very much for taking the time to test and reply even though you no longer use the plugin. I will merge ASAP for anyone else still interested.

**Comment by lambtho12** [comment]
Well, workflows are a personal thing, so for each their own.

As written in the README bu @renerocksai, 
>Leaving the opening of the note to Telescope, you can decide with one keypress whether you want to open the note in a split or in the current window - or if you've seen enough.
>
> I find that pressing the enter key to confirm the search does not interrupt my flow, and I really enjoy being able to check the preview. I often get enough information from it alone so I don't actually have to "visit" every note in terms of being able to edit it.

So this explains the current way of doing things. For me, the more options the better. So we could maybe let the user decide through an option how Telekasten should behave (or at least have arguments to the lua functions so users can make their own specific shortcuts).

_This reminds me that I still have to merge that stuff btw..._
