### ISSUE TITLE
[FR] Custom Date Format

### ISSUE THREAD

**Issue by FeiyouG** [renerocksai/telekasten.nvim#94]
**Please confirm**
- [x] I am running the latest version of this plugin

**Is your feature request related to a problem? Please describe.**
I think it will be nice to allow the users to specify date format. For example, I prefer to have timestamp in this format: 20220217. 

**Describe alternatives you've considered**
Or at least provide template for {{month}}, {{dayOfMonth}} so we can customize the date format ourselves.

**Comment by lambtho12** [comment]
I think it is not that straightforward...

Both ideas need to be implemented I beleive, simply adding {{month}} will only output the current month. But then what happen when you want to template other dates than the current one?

So we should have a config for the datetime_format (default would be `YYYY-mm-dd`)
AND we could have templates to get the current day `{{now_day}}`, month `{{now_month}}` or year `{{now_year}}` alone.

**Comment by yetipowers** [comment]
How would I modify the variable for the long date `{{hdate}}` to display in a certain language, say, German? 

And how could I create custom date templates and variables, e.g. for monthly vs. weekly?

**Comment by lambtho12** [comment]
I think that it would be nice to completely separate the template stuff in a separate file. This might facilitate PRs and community improvements. People have lots of interesting ideas, often quite simple to implement (like `{{now_month}}`,  `{{last_month}}`,  `{{next_month}}`, `{{timezone}}`). In my opinion when it comes to templates and snippets like that, the more we have, the better. We could also have stuff not directly related to time, such as  `{{filename}}`, `{{pwd}}`, `{{dir}}`, `{{host}}`,  `{{user}}`, `{{some git stuff?}}`...

**Comment by lambtho12** [comment]
Closing this as it is now possible to use `{{year}}{{month}}{{day}}` in the templates. So by combining all these as you wish, any date format should be possible.
