### ISSUE TITLE
[FR] Weekly notes string should not be hardcoded

### ISSUE THREAD

**Issue by j-steinbach** [renerocksai/telekasten.nvim#99]
**Please confirm**
- [X] I am running the latest version of this plugin

**Is your feature request related to a problem? Please describe.**

Every Sunday I write a weekly note. It sometimes happens that I forget to write the note on Sunday, so I write it on Monday instead. Or on Tuesday.. This often creates an entry for the wrong week or tries to append to an existing weekly entry. 

**Describe the solution you'd like**

Add the day of the week to the weekly note string. `2021-W46-Monday.md` or `2021-11-21-W46.md` or `2021-11-21-Weekly-W46-Monday.md`. 

This gives me the context that I wrote multiple notes that week. This would also allow me to merge the daily, weekly (and monthly and yearly) journal into the same folder. See my old system:

```
2021-12-31-Friday.md                        2022-02-15-Tuesday.md
2022-01-01-Jahresrückblick-2022.md          2022-02-16-Wednesday.md
2022-01-01-Monatsrückblick-January-2022.md  2022-02-17-Thursday.md
2022-01-01-Saturday.md                      2022-02-18-Friday.md
2022-01-01-Wochenrundschau-W52-2022.md      2022-02-19-Saturday.md
```

**Describe alternatives you've considered**

[Don't hardcode. Let the user choose.](https://github.com/renerocksai/telekasten.nvim#4-the-hardcoded-stuff)

**Comment by lambtho12** [comment]
Ideally nothing should be hardcoded... And considering the other comments from @renerocksai, it seems that he is all in for more config options.

The issue is that this is not trivial to do. Naming file following a template is easy, the problem is searching and opening files quickly. Currently Telekasten interprets the links to determine if they are about notes or dailies/weeklies. Having a single pattern makes it more easy to detect the note type. You could just run the finders on all telekasten directories (and subdirectories), but that would be inefficient and may be time consuming.

**Comment by j-steinbach** [comment]
Oh, didn't think about that. I obviously have no understanding of the code-base, but wouldn't it be possible to use YAML frontmatter for the "search and open" part? Change the weekly template to include a `weekly` tag and then list only those files. But this probably is not as fast as simply looking up the file name.

Alternatively allow the user to change the hardcoded parts and disable some functionality? (Probably not a good idea, coupled with lots of maintenance overhead)

**Comment by lambtho12** [comment]
I just re-read this issue and thought about something...

Do you know that when you want to create a note, you can edit what is in the telescope picker before pressing enter?
Basically if we are monday of W32, the picker will be initialized with `2022-W32`. If this entry concerns W31, you can just hit backspace, replace the `1` by a `2` and press enter. Telekasten will then create (or open) the note 2022-W31.
 
Did you consider that? I do not feel that two more key presses is a major hustle, especially when considering the alternative which would require redesigining the way telekasten looks for files and potentially impact many people.

If you are happy with this solution, feel free to close the issue.

**Comment by j-steinbach** [comment]
For a weekly note I am also fine with two more keystrokes. Now, the base issue still stands (Hardcoded stuff), but as it isn't going to be resolved soon, I can close this.

**Comment by lambtho12** [comment]
Perfect, thank you!
